export default [
  {
    mode: 'metro train',
    routeGTFSID: '2-PKM',
    operationDays: '20250811',
    tripID: '02-PKM--10-T5_ea-4043',
    shapeID: '2-PKM-vpt-10.15.H',
    block: null,
    gtfsDirection: null,
    runID: '4043',
    isRailReplacementBus: false,
    vehicle: null,
    direction: 'Down',
    routeName: 'Pakenham',
    routeNumber: null,
    origin: 'Berwick Railway Station',
    destination: 'East Pakenham Railway Station',
    departureTime: '11:08',
    destinationArrivalTime: '11:27',
    stopTimings: [
      {
        stopName: 'Berwick Railway Station',
        stopNumber: null,
        suburb: 'Berwick',
        stopGTFSID: 'vic:rail:BEW',
        arrivalTime: '11:08',
        arrivalTimeMinutes: 668,
        departureTime: '11:08',
        departureTimeMinutes: 668,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:08:00.000Z',
        actualDepartureTimeMS: 1754874480000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Beaconsfield Railway Station',
        stopNumber: null,
        suburb: 'Beaconsfield',
        stopGTFSID: 'vic:rail:BFD',
        arrivalTime: '11:11',
        arrivalTimeMinutes: 671,
        departureTime: '11:11',
        departureTimeMinutes: 671,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:11:00.000Z',
        actualDepartureTimeMS: 1754874660000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Officer Railway Station',
        stopNumber: null,
        suburb: 'Officer',
        stopGTFSID: 'vic:rail:OFC',
        arrivalTime: '11:15',
        arrivalTimeMinutes: 675,
        departureTime: '11:15',
        departureTimeMinutes: 675,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:15:00.000Z',
        actualDepartureTimeMS: 1754874900000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Cardinia Road Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:CDA',
        arrivalTime: '11:18',
        arrivalTimeMinutes: 678,
        departureTime: '11:18',
        departureTimeMinutes: 678,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:18:00.000Z',
        actualDepartureTimeMS: 1754875080000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:PKM',
        arrivalTime: '11:24',
        arrivalTimeMinutes: 684,
        departureTime: '11:24',
        departureTimeMinutes: 684,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:24:00.000Z',
        actualDepartureTimeMS: 1754875440000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '11:27',
        arrivalTimeMinutes: 687,
        departureTime: '11:27',
        departureTimeMinutes: 687,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:27:00.000Z',
        actualDepartureTimeMS: 1754875620000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '4064',
    forming: '4070',
    cancelled: false,
    additional: false,
    lastUpdated: 1754876158863
  },
  {
    mode: 'metro train',
    routeGTFSID: '2-PKM',
    operationDays: '20250811',
    tripID: '02-PKM--10-T5_ea-4045',
    shapeID: '2-PKM-vpt-10.15.H',
    block: null,
    gtfsDirection: null,
    runID: '4045',
    isRailReplacementBus: false,
    vehicle: null,
    direction: 'Down',
    routeName: 'Pakenham',
    routeNumber: null,
    origin: 'Berwick Railway Station',
    destination: 'East Pakenham Railway Station',
    departureTime: '11:28',
    destinationArrivalTime: '11:47',
    stopTimings: [
      {
        stopName: 'Berwick Railway Station',
        stopNumber: null,
        suburb: 'Berwick',
        stopGTFSID: 'vic:rail:BEW',
        arrivalTime: '11:28',
        arrivalTimeMinutes: 688,
        departureTime: '11:28',
        departureTimeMinutes: 688,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:28:00.000Z',
        actualDepartureTimeMS: 1754875680000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Beaconsfield Railway Station',
        stopNumber: null,
        suburb: 'Beaconsfield',
        stopGTFSID: 'vic:rail:BFD',
        arrivalTime: '11:31',
        arrivalTimeMinutes: 691,
        departureTime: '11:31',
        departureTimeMinutes: 691,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:31:00.000Z',
        actualDepartureTimeMS: 1754875860000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Officer Railway Station',
        stopNumber: null,
        suburb: 'Officer',
        stopGTFSID: 'vic:rail:OFC',
        arrivalTime: '11:35',
        arrivalTimeMinutes: 695,
        departureTime: '11:35',
        departureTimeMinutes: 695,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:35:00.000Z',
        actualDepartureTimeMS: 1754876100000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Cardinia Road Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:CDA',
        arrivalTime: '11:38',
        arrivalTimeMinutes: 698,
        departureTime: '11:38',
        departureTimeMinutes: 698,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:38:00.000Z',
        actualDepartureTimeMS: 1754876280000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:PKM',
        arrivalTime: '11:44',
        arrivalTimeMinutes: 704,
        departureTime: '11:44',
        departureTimeMinutes: 704,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:44:00.000Z',
        actualDepartureTimeMS: 1754876640000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '11:47',
        arrivalTimeMinutes: 707,
        departureTime: '11:47',
        departureTimeMinutes: 707,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:47:00.000Z',
        actualDepartureTimeMS: 1754876820000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '4066',
    forming: '4072',
    cancelled: false,
    additional: false,
    lastUpdated: 1754876158865
  },
  {
    mode: 'metro train',
    routeGTFSID: '2-PKM',
    operationDays: '20250811',
    tripID: '02-PKM--10-T5_ea-4047',
    shapeID: '2-PKM-vpt-10.15.H',
    block: null,
    gtfsDirection: null,
    runID: '4047',
    isRailReplacementBus: false,
    vehicle: null,
    direction: 'Down',
    routeName: 'Pakenham',
    routeNumber: null,
    origin: 'Berwick Railway Station',
    destination: 'East Pakenham Railway Station',
    departureTime: '11:48',
    destinationArrivalTime: '12:07',
    stopTimings: [
      {
        stopName: 'Berwick Railway Station',
        stopNumber: null,
        suburb: 'Berwick',
        stopGTFSID: 'vic:rail:BEW',
        arrivalTime: '11:48',
        arrivalTimeMinutes: 708,
        departureTime: '11:48',
        departureTimeMinutes: 708,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:48:00.000Z',
        actualDepartureTimeMS: 1754876880000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Beaconsfield Railway Station',
        stopNumber: null,
        suburb: 'Beaconsfield',
        stopGTFSID: 'vic:rail:BFD',
        arrivalTime: '11:51',
        arrivalTimeMinutes: 711,
        departureTime: '11:51',
        departureTimeMinutes: 711,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:51:00.000Z',
        actualDepartureTimeMS: 1754877060000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Officer Railway Station',
        stopNumber: null,
        suburb: 'Officer',
        stopGTFSID: 'vic:rail:OFC',
        arrivalTime: '11:55',
        arrivalTimeMinutes: 715,
        departureTime: '11:55',
        departureTimeMinutes: 715,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:55:00.000Z',
        actualDepartureTimeMS: 1754877300000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Cardinia Road Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:CDA',
        arrivalTime: '11:58',
        arrivalTimeMinutes: 718,
        departureTime: '11:58',
        departureTimeMinutes: 718,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:58:00.000Z',
        actualDepartureTimeMS: 1754877480000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:PKM',
        arrivalTime: '12:04',
        arrivalTimeMinutes: 724,
        departureTime: '12:04',
        departureTimeMinutes: 724,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:04:00.000Z',
        actualDepartureTimeMS: 1754877840000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '12:07',
        arrivalTimeMinutes: 727,
        departureTime: '12:07',
        departureTimeMinutes: 727,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:07:00.000Z',
        actualDepartureTimeMS: 1754878020000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '4068',
    forming: '4074',
    cancelled: false,
    additional: false,
    lastUpdated: 1754876158868
  },
  {
    mode: 'metro train',
    routeGTFSID: '2-PKM',
    operationDays: '20250811',
    tripID: '02-PKM--10-T5_ea-4070',
    shapeID: '2-PKM-vpt-10.16.R',
    block: null,
    gtfsDirection: null,
    runID: '4070',
    isRailReplacementBus: false,
    vehicle: null,
    direction: 'Up',
    routeName: 'Pakenham',
    routeNumber: null,
    origin: 'East Pakenham Railway Station',
    destination: 'Berwick Railway Station',
    departureTime: '11:43',
    destinationArrivalTime: '12:00',
    stopTimings: [
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '11:43',
        arrivalTimeMinutes: 703,
        departureTime: '11:43',
        departureTimeMinutes: 703,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:43:00.000Z',
        actualDepartureTimeMS: 1754876580000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:PKM',
        arrivalTime: '11:46',
        arrivalTimeMinutes: 706,
        departureTime: '11:46',
        departureTimeMinutes: 706,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:46:00.000Z',
        actualDepartureTimeMS: 1754876760000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Cardinia Road Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:CDA',
        arrivalTime: '11:50',
        arrivalTimeMinutes: 710,
        departureTime: '11:50',
        departureTimeMinutes: 710,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:50:00.000Z',
        actualDepartureTimeMS: 1754877000000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Officer Railway Station',
        stopNumber: null,
        suburb: 'Officer',
        stopGTFSID: 'vic:rail:OFC',
        arrivalTime: '11:53',
        arrivalTimeMinutes: 713,
        departureTime: '11:53',
        departureTimeMinutes: 713,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:53:00.000Z',
        actualDepartureTimeMS: 1754877180000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Beaconsfield Railway Station',
        stopNumber: null,
        suburb: 'Beaconsfield',
        stopGTFSID: 'vic:rail:BFD',
        arrivalTime: '11:57',
        arrivalTimeMinutes: 717,
        departureTime: '11:57',
        departureTimeMinutes: 717,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:57:00.000Z',
        actualDepartureTimeMS: 1754877420000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Berwick Railway Station',
        stopNumber: null,
        suburb: 'Berwick',
        stopGTFSID: 'vic:rail:BEW',
        arrivalTime: '12:00',
        arrivalTimeMinutes: 720,
        departureTime: '12:00',
        departureTimeMinutes: 720,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:00:00.000Z',
        actualDepartureTimeMS: 1754877600000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '4043',
    forming: '4049',
    cancelled: false,
    additional: false,
    lastUpdated: 1754876158893
  },
  {
    mode: 'metro train',
    routeGTFSID: '2-PKM',
    operationDays: '20250811',
    tripID: '02-PKM--10-T5_ea-4072',
    shapeID: '2-PKM-vpt-10.16.R',
    block: null,
    gtfsDirection: null,
    runID: '4072',
    isRailReplacementBus: false,
    vehicle: null,
    direction: 'Up',
    routeName: 'Pakenham',
    routeNumber: null,
    origin: 'East Pakenham Railway Station',
    destination: 'Berwick Railway Station',
    departureTime: '12:03',
    destinationArrivalTime: '12:20',
    stopTimings: [
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '12:03',
        arrivalTimeMinutes: 723,
        departureTime: '12:03',
        departureTimeMinutes: 723,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:03:00.000Z',
        actualDepartureTimeMS: 1754877780000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:PKM',
        arrivalTime: '12:06',
        arrivalTimeMinutes: 726,
        departureTime: '12:06',
        departureTimeMinutes: 726,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:06:00.000Z',
        actualDepartureTimeMS: 1754877960000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Cardinia Road Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:CDA',
        arrivalTime: '12:10',
        arrivalTimeMinutes: 730,
        departureTime: '12:10',
        departureTimeMinutes: 730,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:10:00.000Z',
        actualDepartureTimeMS: 1754878200000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Officer Railway Station',
        stopNumber: null,
        suburb: 'Officer',
        stopGTFSID: 'vic:rail:OFC',
        arrivalTime: '12:13',
        arrivalTimeMinutes: 733,
        departureTime: '12:13',
        departureTimeMinutes: 733,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:13:00.000Z',
        actualDepartureTimeMS: 1754878380000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Beaconsfield Railway Station',
        stopNumber: null,
        suburb: 'Beaconsfield',
        stopGTFSID: 'vic:rail:BFD',
        arrivalTime: '12:17',
        arrivalTimeMinutes: 737,
        departureTime: '12:17',
        departureTimeMinutes: 737,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:17:00.000Z',
        actualDepartureTimeMS: 1754878620000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Berwick Railway Station',
        stopNumber: null,
        suburb: 'Berwick',
        stopGTFSID: 'vic:rail:BEW',
        arrivalTime: '12:20',
        arrivalTimeMinutes: 740,
        departureTime: '12:20',
        departureTimeMinutes: 740,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:20:00.000Z',
        actualDepartureTimeMS: 1754878800000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '4045',
    forming: '4051',
    cancelled: false,
    additional: false,
    lastUpdated: 1754876158895
  },
  {
    mode: 'metro train',
    routeGTFSID: '2-PKM',
    operationDays: '20250811',
    tripID: '02-PKM--10-T5_ea-4074',
    shapeID: '2-PKM-vpt-10.16.R',
    block: null,
    gtfsDirection: null,
    runID: '4074',
    isRailReplacementBus: false,
    vehicle: null,
    direction: 'Up',
    routeName: 'Pakenham',
    routeNumber: null,
    origin: 'East Pakenham Railway Station',
    destination: 'Berwick Railway Station',
    departureTime: '12:23',
    destinationArrivalTime: '12:40',
    stopTimings: [
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '12:23',
        arrivalTimeMinutes: 743,
        departureTime: '12:23',
        departureTimeMinutes: 743,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:23:00.000Z',
        actualDepartureTimeMS: 1754878980000,
        platform: '2',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:PKM',
        arrivalTime: '12:26',
        arrivalTimeMinutes: 746,
        departureTime: '12:26',
        departureTimeMinutes: 746,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:26:00.000Z',
        actualDepartureTimeMS: 1754879160000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Cardinia Road Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:CDA',
        arrivalTime: '12:30',
        arrivalTimeMinutes: 750,
        departureTime: '12:30',
        departureTimeMinutes: 750,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:30:00.000Z',
        actualDepartureTimeMS: 1754879400000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Officer Railway Station',
        stopNumber: null,
        suburb: 'Officer',
        stopGTFSID: 'vic:rail:OFC',
        arrivalTime: '12:33',
        arrivalTimeMinutes: 753,
        departureTime: '12:33',
        departureTimeMinutes: 753,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:33:00.000Z',
        actualDepartureTimeMS: 1754879580000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Beaconsfield Railway Station',
        stopNumber: null,
        suburb: 'Beaconsfield',
        stopGTFSID: 'vic:rail:BFD',
        arrivalTime: '12:37',
        arrivalTimeMinutes: 757,
        departureTime: '12:37',
        departureTimeMinutes: 757,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:37:00.000Z',
        actualDepartureTimeMS: 1754879820000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Berwick Railway Station',
        stopNumber: null,
        suburb: 'Berwick',
        stopGTFSID: 'vic:rail:BEW',
        arrivalTime: '12:40',
        arrivalTimeMinutes: 760,
        departureTime: '12:40',
        departureTimeMinutes: 760,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:40:00.000Z',
        actualDepartureTimeMS: 1754880000000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '4047',
    forming: '4053',
    cancelled: false,
    additional: false,
    lastUpdated: 1754876158897
  },
  {
    mode: 'regional train',
    routeGTFSID: '1-TRN',
    operationDays: '20250811',
    tripID: '9.T0.1-TRN-mjp-5.1.H',
    shapeID: '1-TRN-mjp-5.1.H',
    block: null,
    gtfsDirection: null,
    runID: '8409',
    isRailReplacementBus: null,
    vehicle: null,
    direction: 'Down',
    routeName: 'Traralgon',
    routeNumber: null,
    origin: 'East Pakenham Railway Station',
    destination: 'Traralgon Railway Station',
    departureTime: '12:04',
    destinationArrivalTime: '13:21',
    stopTimings: [
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '12:04',
        arrivalTimeMinutes: 724,
        departureTime: '12:04',
        departureTimeMinutes: 724,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:04:00.000Z',
        actualDepartureTimeMS: 1754877840000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Nar Nar Goon Railway Station',
        stopNumber: null,
        suburb: 'Nar Nar Goon',
        stopGTFSID: 'vic:rail:NNG',
        arrivalTime: '12:09',
        arrivalTimeMinutes: 729,
        departureTime: '12:09',
        departureTimeMinutes: 729,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:09:00.000Z',
        actualDepartureTimeMS: 1754878140000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Tynong Railway Station',
        stopNumber: null,
        suburb: 'Tynong',
        stopGTFSID: 'vic:rail:TYN',
        arrivalTime: '12:13',
        arrivalTimeMinutes: 733,
        departureTime: '12:13',
        departureTimeMinutes: 733,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:13:00.000Z',
        actualDepartureTimeMS: 1754878380000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Garfield Railway Station',
        stopNumber: null,
        suburb: 'Garfield',
        stopGTFSID: 'vic:rail:GAR-V',
        arrivalTime: '12:17',
        arrivalTimeMinutes: 737,
        departureTime: '12:17',
        departureTimeMinutes: 737,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:17:00.000Z',
        actualDepartureTimeMS: 1754878620000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Bunyip Railway Station',
        stopNumber: null,
        suburb: 'Bunyip',
        stopGTFSID: 'vic:rail:BYP',
        arrivalTime: '12:21',
        arrivalTimeMinutes: 741,
        departureTime: '12:21',
        departureTimeMinutes: 741,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:21:00.000Z',
        actualDepartureTimeMS: 1754878860000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Longwarry Railway Station',
        stopNumber: null,
        suburb: 'Longwarry',
        stopGTFSID: 'vic:rail:LWY',
        arrivalTime: '12:25',
        arrivalTimeMinutes: 745,
        departureTime: '12:25',
        departureTimeMinutes: 745,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:25:00.000Z',
        actualDepartureTimeMS: 1754879100000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Drouin Railway Station',
        stopNumber: null,
        suburb: 'Drouin',
        stopGTFSID: 'vic:rail:DRN',
        arrivalTime: '12:32',
        arrivalTimeMinutes: 752,
        departureTime: '12:32',
        departureTimeMinutes: 752,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:32:00.000Z',
        actualDepartureTimeMS: 1754879520000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Warragul Railway Station',
        stopNumber: null,
        suburb: 'Warragul',
        stopGTFSID: 'vic:rail:WGL',
        arrivalTime: '12:38',
        arrivalTimeMinutes: 758,
        departureTime: '12:38',
        departureTimeMinutes: 758,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:38:00.000Z',
        actualDepartureTimeMS: 1754879880000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Yarragon Railway Station',
        stopNumber: null,
        suburb: 'Yarragon',
        stopGTFSID: 'vic:rail:YON',
        arrivalTime: '12:46',
        arrivalTimeMinutes: 766,
        departureTime: '12:46',
        departureTimeMinutes: 766,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:46:00.000Z',
        actualDepartureTimeMS: 1754880360000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Trafalgar Railway Station',
        stopNumber: null,
        suburb: 'Trafalgar',
        stopGTFSID: 'vic:rail:TAR',
        arrivalTime: '12:52',
        arrivalTimeMinutes: 772,
        departureTime: '12:52',
        departureTimeMinutes: 772,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:52:00.000Z',
        actualDepartureTimeMS: 1754880720000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Moe Railway Station',
        stopNumber: null,
        suburb: 'Moe',
        stopGTFSID: 'vic:rail:MOE',
        arrivalTime: '12:59',
        arrivalTimeMinutes: 779,
        departureTime: '12:59',
        departureTimeMinutes: 779,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T02:59:00.000Z',
        actualDepartureTimeMS: 1754881140000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Morwell Railway Station',
        stopNumber: null,
        suburb: 'Morwell',
        stopGTFSID: 'vic:rail:MWL',
        arrivalTime: '13:11',
        arrivalTimeMinutes: 791,
        departureTime: '13:11',
        departureTimeMinutes: 791,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T03:11:00.000Z',
        actualDepartureTimeMS: 1754881860000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Traralgon Railway Station',
        stopNumber: null,
        suburb: 'Traralgon',
        stopGTFSID: 'vic:rail:TRN',
        arrivalTime: '13:21',
        arrivalTimeMinutes: 801,
        departureTime: '13:21',
        departureTimeMinutes: 801,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T03:21:00.000Z',
        actualDepartureTimeMS: 1754882460000,
        platform: null,
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '8226',
    forming: '8434',
    cancelled: false,
    additional: false,
    lastUpdated: 1754872498555
  },
  {
    mode: 'regional train',
    routeGTFSID: '1-TRN',
    operationDays: '20250811',
    tripID: '22.T0.1-TRN-mjp-5.4.R',
    shapeID: '1-TRN-mjp-5.4.R',
    block: null,
    gtfsDirection: null,
    runID: '8416',
    isRailReplacementBus: null,
    vehicle: null,
    direction: 'Up',
    routeName: 'Traralgon',
    routeNumber: null,
    origin: 'Traralgon Railway Station',
    destination: 'East Pakenham Railway Station',
    departureTime: '10:34',
    destinationArrivalTime: '11:48',
    stopTimings: [
      {
        stopName: 'Traralgon Railway Station',
        stopNumber: null,
        suburb: 'Traralgon',
        stopGTFSID: 'vic:rail:TRN',
        arrivalTime: '10:34',
        arrivalTimeMinutes: 634,
        departureTime: '10:34',
        departureTimeMinutes: 634,
        estimatedDepartureTime: '2025-08-11T00:34:00.000Z',
        scheduledDepartureTime: '2025-08-11T00:34:00.000Z',
        actualDepartureTimeMS: 1754872440000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 1 }
      },
      {
        stopName: 'Morwell Railway Station',
        stopNumber: null,
        suburb: 'Morwell',
        stopGTFSID: 'vic:rail:MWL',
        arrivalTime: '10:42',
        arrivalTimeMinutes: 642,
        departureTime: '10:42',
        departureTimeMinutes: 642,
        estimatedDepartureTime: '2025-08-11T00:42:00.000Z',
        scheduledDepartureTime: '2025-08-11T00:42:00.000Z',
        actualDepartureTimeMS: 1754872920000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Moe Railway Station',
        stopNumber: null,
        suburb: 'Moe',
        stopGTFSID: 'vic:rail:MOE',
        arrivalTime: '10:51',
        arrivalTimeMinutes: 651,
        departureTime: '10:51',
        departureTimeMinutes: 651,
        estimatedDepartureTime: '2025-08-11T00:51:00.000Z',
        scheduledDepartureTime: '2025-08-11T00:51:00.000Z',
        actualDepartureTimeMS: 1754873460000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Trafalgar Railway Station',
        stopNumber: null,
        suburb: 'Trafalgar',
        stopGTFSID: 'vic:rail:TAR',
        arrivalTime: '10:57',
        arrivalTimeMinutes: 657,
        departureTime: '10:57',
        departureTimeMinutes: 657,
        estimatedDepartureTime: '2025-08-11T00:57:00.000Z',
        scheduledDepartureTime: '2025-08-11T00:57:00.000Z',
        actualDepartureTimeMS: 1754873820000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Yarragon Railway Station',
        stopNumber: null,
        suburb: 'Yarragon',
        stopGTFSID: 'vic:rail:YON',
        arrivalTime: '11:03',
        arrivalTimeMinutes: 663,
        departureTime: '11:03',
        departureTimeMinutes: 663,
        estimatedDepartureTime: '2025-08-11T01:03:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:03:00.000Z',
        actualDepartureTimeMS: 1754874180000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Warragul Railway Station',
        stopNumber: null,
        suburb: 'Warragul',
        stopGTFSID: 'vic:rail:WGL',
        arrivalTime: '11:11',
        arrivalTimeMinutes: 671,
        departureTime: '11:11',
        departureTimeMinutes: 671,
        estimatedDepartureTime: '2025-08-11T01:11:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:11:00.000Z',
        actualDepartureTimeMS: 1754874660000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Drouin Railway Station',
        stopNumber: null,
        suburb: 'Drouin',
        stopGTFSID: 'vic:rail:DRN',
        arrivalTime: '11:17',
        arrivalTimeMinutes: 677,
        departureTime: '11:17',
        departureTimeMinutes: 677,
        estimatedDepartureTime: '2025-08-11T01:17:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:17:00.000Z',
        actualDepartureTimeMS: 1754875020000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Longwarry Railway Station',
        stopNumber: null,
        suburb: 'Longwarry',
        stopGTFSID: 'vic:rail:LWY',
        arrivalTime: '11:23',
        arrivalTimeMinutes: 683,
        departureTime: '11:23',
        departureTimeMinutes: 683,
        estimatedDepartureTime: '2025-08-11T01:23:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:23:00.000Z',
        actualDepartureTimeMS: 1754875380000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Bunyip Railway Station',
        stopNumber: null,
        suburb: 'Bunyip',
        stopGTFSID: 'vic:rail:BYP',
        arrivalTime: '11:27',
        arrivalTimeMinutes: 687,
        departureTime: '11:27',
        departureTimeMinutes: 687,
        estimatedDepartureTime: '2025-08-11T01:27:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:27:00.000Z',
        actualDepartureTimeMS: 1754875620000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Garfield Railway Station',
        stopNumber: null,
        suburb: 'Garfield',
        stopGTFSID: 'vic:rail:GAR-V',
        arrivalTime: '11:30',
        arrivalTimeMinutes: 690,
        departureTime: '11:30',
        departureTimeMinutes: 690,
        estimatedDepartureTime: '2025-08-11T01:30:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:30:00.000Z',
        actualDepartureTimeMS: 1754875800000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Tynong Railway Station',
        stopNumber: null,
        suburb: 'Tynong',
        stopGTFSID: 'vic:rail:TYN',
        arrivalTime: '11:34',
        arrivalTimeMinutes: 694,
        departureTime: '11:34',
        departureTimeMinutes: 694,
        estimatedDepartureTime: '2025-08-11T01:34:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:34:00.000Z',
        actualDepartureTimeMS: 1754876040000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'Nar Nar Goon Railway Station',
        stopNumber: null,
        suburb: 'Nar Nar Goon',
        stopGTFSID: 'vic:rail:NNG',
        arrivalTime: '11:38',
        arrivalTimeMinutes: 698,
        departureTime: '11:38',
        departureTimeMinutes: 698,
        estimatedDepartureTime: '2025-08-11T01:38:00.000Z',
        scheduledDepartureTime: '2025-08-11T01:38:00.000Z',
        actualDepartureTimeMS: 1754876280000,
        platform: '1',
        cancelled: false,
        additional: false,
        stopConditions: { pickup: 0, dropoff: 0 }
      },
      {
        stopName: 'East Pakenham Railway Station',
        stopNumber: null,
        suburb: 'Pakenham',
        stopGTFSID: 'vic:rail:EPH',
        arrivalTime: '11:48',
        arrivalTimeMinutes: 708,
        departureTime: '11:48',
        departureTimeMinutes: 708,
        estimatedDepartureTime: null,
        scheduledDepartureTime: '2025-08-11T01:48:00.000Z',
        actualDepartureTimeMS: 1754876880000,
        platform: null,
        cancelled: true,
        additional: false,
        stopConditions: { pickup: 1, dropoff: 0 }
      }
    ],
    formedBy: '8403',
    forming: '8023',
    cancelled: false,
    additional: false,
    lastUpdated: 1754871716206
  }
]