export default [
  {
    mode: 'metro train',
    routeName: 'Frankston',
    routeNumber: null,
    routeGTFSID: '2-FKN',
    operationDays: [
      '20260206', '20260213',
      '20260220', '20260227',
      '20260306', '20260313',
      '20260320', '20260327',
      '20260410'
    ],
    calendarID: 'T6_3',
    tripID: '02-FKN--1-T6-4479',
    shapeID: '2-FKN-vpt-1.4.H',
    block: '17857',
    gtfsDirection: 0,
    runID: '4479',
    isRailReplacementBus: false,
    direction: 'Down',
    stopTimings: [
      {
        stopName: 'Flinders Street Railway Station',
        stopNumber: null,
        suburb: 'Melbourne',
        stopGTFSID: 'vic:rail:FSS',
        arrivalTime: '19:35',
        arrivalTimeMinutes: 1175,
        departureTime: '19:35',
        departureTimeMinutes: 1175,
        stopConditions: { pickup: 0, dropoff: 1 },
        stopDistance: 0,
        platform: '6'
      },
      {
        stopName: 'Richmond Railway Station',
        stopNumber: null,
        suburb: 'Richmond',
        stopGTFSID: 'vic:rail:RMD',
        arrivalTime: '19:38',
        arrivalTimeMinutes: 1178,
        departureTime: '19:38',
        departureTimeMinutes: 1178,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 2270.27,
        platform: '4'
      },
      {
        stopName: 'South Yarra Railway Station',
        stopNumber: null,
        suburb: 'South Yarra',
        stopGTFSID: 'vic:rail:SYR',
        arrivalTime: '19:41',
        arrivalTimeMinutes: 1181,
        departureTime: '19:41',
        departureTimeMinutes: 1181,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 4090.78,
        platform: '4'
      },
      {
        stopName: 'Frankston Railway Station',
        stopNumber: null,
        suburb: 'Frankston',
        stopGTFSID: 'vic:rail:FKN',
        arrivalTime: '20:39',
        arrivalTimeMinutes: 1239,
        departureTime: '20:39',
        departureTimeMinutes: 1239,
        stopConditions: { pickup: 1, dropoff: 0 },
        stopDistance: 42586.32,
        platform: '2'
      }
    ],
    origin: 'Flinders Street Railway Station',
    departureTime: '19:35',
    destination: 'Frankston Railway Station',
    destinationArrivalTime: '20:39',
    trueOrigin: 'Flinders Street Railway Station',
    trueDestination: 'Frankston Railway Station',
    trueDepartureTime: '19:35',
    trueDestinationArrivalTime: '20:39'
  },
  {
    mode: 'metro train',
    routeName: 'Frankston',
    routeNumber: null,
    routeGTFSID: '2-FKN',
    operationDays: [
      '20260206', '20260213',
      '20260220', '20260227',
      '20260306', '20260313',
      '20260320', '20260327',
      '20260410'
    ],
    calendarID: 'T6_3',
    tripID: '02-FKN--1-T6-4968',
    shapeID: '2-FKN-vpt-1.10.R',
    block: '17857',
    gtfsDirection: 1,
    runID: '4968',
    isRailReplacementBus: false,
    direction: 'Up',
    stopTimings: [
      {
        stopName: 'Frankston Railway Station',
        stopNumber: null,
        suburb: 'Frankston',
        stopGTFSID: 'vic:rail:FKN',
        arrivalTime: '18:16',
        arrivalTimeMinutes: 1096,
        departureTime: '18:16',
        departureTimeMinutes: 1096,
        stopConditions: { pickup: 0, dropoff: 1 },
        stopDistance: 0,
        platform: '2'
      },
      {
        stopName: 'South Yarra Railway Station',
        stopNumber: null,
        suburb: 'South Yarra',
        stopGTFSID: 'vic:rail:SYR',
        arrivalTime: '19:14',
        arrivalTimeMinutes: 1154,
        departureTime: '19:14',
        departureTimeMinutes: 1154,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 65074.68,
        platform: '3'
      },
      {
        stopName: 'Richmond Railway Station',
        stopNumber: null,
        suburb: 'Richmond',
        stopGTFSID: 'vic:rail:RMD',
        arrivalTime: '19:17',
        arrivalTimeMinutes: 1157,
        departureTime: '19:17',
        departureTimeMinutes: 1157,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 66889.26,
        platform: '3'
      },
      {
        stopName: 'Parliament Railway Station',
        stopNumber: null,
        suburb: 'East Melbourne',
        stopGTFSID: 'vic:rail:PAR',
        arrivalTime: '19:20',
        arrivalTimeMinutes: 1160,
        departureTime: '19:20',
        departureTimeMinutes: 1160,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 69055.12,
        platform: '2'
      },
      {
        stopName: 'Melbourne Central Railway Station',
        stopNumber: null,
        suburb: 'Melbourne',
        stopGTFSID: 'vic:rail:MCE',
        arrivalTime: '19:22',
        arrivalTimeMinutes: 1162,
        departureTime: '19:22',
        departureTimeMinutes: 1162,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 70190.16,
        platform: '2'
      },
      {
        stopName: 'Flagstaff Railway Station',
        stopNumber: null,
        suburb: 'West Melbourne',
        stopGTFSID: 'vic:rail:FGS',
        arrivalTime: '19:24',
        arrivalTimeMinutes: 1164,
        departureTime: '19:24',
        departureTimeMinutes: 1164,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 70840.18,
        platform: '2'
      },
      {
        stopName: 'Southern Cross Railway Station',
        stopNumber: null,
        suburb: 'Docklands',
        stopGTFSID: 'vic:rail:SSS',
        arrivalTime: '19:26',
        arrivalTimeMinutes: 1166,
        departureTime: '19:26',
        departureTimeMinutes: 1166,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 71951.09,
        platform: '12'
      },
      {
        stopName: 'Flinders Street Railway Station',
        stopNumber: null,
        suburb: 'Melbourne',
        stopGTFSID: 'vic:rail:FSS',
        arrivalTime: '19:30',
        arrivalTimeMinutes: 1170,
        departureTime: '19:30',
        departureTimeMinutes: 1170,
        stopConditions: { pickup: 1, dropoff: 0 },
        stopDistance: 73465.5,
        platform: '6'
      }
    ],
    origin: 'Frankston Railway Station',
    departureTime: '18:16',
    destination: 'Flinders Street Railway Station',
    destinationArrivalTime: '19:30',
    trueOrigin: 'Frankston Railway Station',
    trueDestination: 'Flinders Street Railway Station',
    trueDepartureTime: '18:16',
    trueDestinationArrivalTime: '19:30'
  }
]