export default [
  {
    mode: 'metro train',
    routeName: 'Pakenham',
    routeNumber: null,
    routeGTFSID: '2-PKM',
    operationDays: [ '20251117', '20251118', '20251119' ],
    calendarID: 'T5+il',
    tripID: '02-PKM-R-24-T5_il-BD112',
    shapeID: '2-PKM-R-vpt-24.1.R',
    block: null,
    gtfsDirection: 1,
    runID: 'BD112',
    isRailReplacementBus: true,
    direction: 'Up',
    stopTimings: [
      {
        stopName: 'Westall Railway Station',
        stopNumber: null,
        suburb: 'Clayton South',
        stopGTFSID: 'vic:rail:WTL',
        arrivalTime: '22:51',
        arrivalTimeMinutes: 1371,
        departureTime: '22:51',
        departureTimeMinutes: 1371,
        stopConditions: { pickup: 0, dropoff: 1 },
        stopDistance: 0,
        platform: 'RRB'
      },
      {
        stopName: 'Clayton Railway Station',
        stopNumber: null,
        suburb: 'Clayton',
        stopGTFSID: 'vic:rail:CLA',
        arrivalTime: '22:55',
        arrivalTimeMinutes: 1375,
        departureTime: '22:55',
        departureTimeMinutes: 1375,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 2466.73,
        platform: 'RRB'
      },
      {
        stopName: 'Huntingdale Railway Station',
        stopNumber: null,
        suburb: 'Oakleigh',
        stopGTFSID: 'vic:rail:HUN',
        arrivalTime: '23:00',
        arrivalTimeMinutes: 1380,
        departureTime: '23:00',
        departureTimeMinutes: 1380,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 5624.68,
        platform: 'RRB'
      },
      {
        stopName: 'Oakleigh Railway Station',
        stopNumber: null,
        suburb: 'Oakleigh',
        stopGTFSID: 'vic:rail:OAK',
        arrivalTime: '23:05',
        arrivalTimeMinutes: 1385,
        departureTime: '23:05',
        departureTimeMinutes: 1385,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 8258.81,
        platform: 'RRB'
      },
      {
        stopName: 'Hughesdale Railway Station',
        stopNumber: null,
        suburb: 'Murrumbeena',
        stopGTFSID: 'vic:rail:HUG',
        arrivalTime: '23:09',
        arrivalTimeMinutes: 1389,
        departureTime: '23:09',
        departureTimeMinutes: 1389,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 9619.59,
        platform: 'RRB'
      },
      {
        stopName: 'Murrumbeena Railway Station',
        stopNumber: null,
        suburb: 'Murrumbeena',
        stopGTFSID: 'vic:rail:MRB',
        arrivalTime: '23:12',
        arrivalTimeMinutes: 1392,
        departureTime: '23:12',
        departureTimeMinutes: 1392,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 10807.57,
        platform: 'RRB'
      },
      {
        stopName: 'Carnegie Railway Station',
        stopNumber: null,
        suburb: 'Carnegie',
        stopGTFSID: 'vic:rail:CNE',
        arrivalTime: '23:16',
        arrivalTimeMinutes: 1396,
        departureTime: '23:16',
        departureTimeMinutes: 1396,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 12115.19,
        platform: 'RRB'
      },
      {
        stopName: 'Caulfield Railway Station',
        stopNumber: null,
        suburb: 'Caulfield East',
        stopGTFSID: 'vic:rail:CFD',
        arrivalTime: '23:36',
        arrivalTimeMinutes: 1416,
        departureTime: '23:36',
        departureTimeMinutes: 1416,
        stopConditions: { pickup: 1, dropoff: 0 },
        stopDistance: 14200.04,
        platform: 'RRB'
      }
    ],
    origin: 'Westall Railway Station',
    departureTime: '22:51',
    destination: 'Caulfield Railway Station',
    destinationArrivalTime: '23:36',
    trueOrigin: 'Westall Railway Station',
    trueDestination: 'Caulfield Railway Station',
    trueDepartureTime: '22:51',
    trueDestinationArrivalTime: '23:36'
  },
  {
    mode: 'metro train',
    routeName: 'Pakenham',
    routeNumber: null,
    routeGTFSID: '2-PKM',
    operationDays: [ '20251117', '20251118', '20251119' ],
    calendarID: 'T5+il',
    tripID: '02-PKM-R-24-T5_il-BD614',
    shapeID: '2-PKM-R-vpt-24.5.R',
    block: null,
    gtfsDirection: 1,
    runID: 'BD614',
    isRailReplacementBus: true,
    direction: 'Up',
    stopTimings: [
      {
        stopName: 'Dandenong Railway Station',
        stopNumber: null,
        suburb: 'Dandenong',
        stopGTFSID: 'vic:rail:DNG',
        arrivalTime: '22:40',
        arrivalTimeMinutes: 1360,
        departureTime: '22:40',
        departureTimeMinutes: 1360,
        stopConditions: { pickup: 0, dropoff: 1 },
        stopDistance: 0,
        platform: 'RRB'
      },
      {
        stopName: 'Yarraman Railway Station',
        stopNumber: null,
        suburb: 'Noble Park',
        stopGTFSID: 'vic:rail:YMN',
        arrivalTime: '22:45',
        arrivalTimeMinutes: 1365,
        departureTime: '22:45',
        departureTimeMinutes: 1365,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 2674.97,
        platform: 'RRB'
      },
      {
        stopName: 'Noble Park Railway Station',
        stopNumber: null,
        suburb: 'Noble Park',
        stopGTFSID: 'vic:rail:NPK',
        arrivalTime: '22:48',
        arrivalTimeMinutes: 1368,
        departureTime: '22:48',
        departureTimeMinutes: 1368,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 4733.79,
        platform: 'RRB'
      },
      {
        stopName: 'Sandown Park Railway Station',
        stopNumber: null,
        suburb: 'Springvale',
        stopGTFSID: 'vic:rail:SNP',
        arrivalTime: '22:52',
        arrivalTimeMinutes: 1372,
        departureTime: '22:52',
        departureTimeMinutes: 1372,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 6408.03,
        platform: 'RRB'
      },
      {
        stopName: 'Springvale Railway Station',
        stopNumber: null,
        suburb: 'Springvale',
        stopGTFSID: 'vic:rail:SPG',
        arrivalTime: '22:54',
        arrivalTimeMinutes: 1374,
        departureTime: '22:54',
        departureTimeMinutes: 1374,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 7526.18,
        platform: 'RRB'
      },
      {
        stopName: 'Westall Railway Station',
        stopNumber: null,
        suburb: 'Clayton South',
        stopGTFSID: 'vic:rail:WTL',
        arrivalTime: '23:00',
        arrivalTimeMinutes: 1380,
        departureTime: '23:00',
        departureTimeMinutes: 1380,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 10325.52,
        platform: 'RRB'
      },
      {
        stopName: 'Clayton Railway Station',
        stopNumber: null,
        suburb: 'Clayton',
        stopGTFSID: 'vic:rail:CLA',
        arrivalTime: '23:04',
        arrivalTimeMinutes: 1384,
        departureTime: '23:04',
        departureTimeMinutes: 1384,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 12792.25,
        platform: 'RRB'
      },
      {
        stopName: 'Huntingdale Railway Station',
        stopNumber: null,
        suburb: 'Oakleigh',
        stopGTFSID: 'vic:rail:HUN',
        arrivalTime: '23:10',
        arrivalTimeMinutes: 1390,
        departureTime: '23:10',
        departureTimeMinutes: 1390,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 15950.19,
        platform: 'RRB'
      },
      {
        stopName: 'Caulfield Railway Station',
        stopNumber: null,
        suburb: 'Caulfield East',
        stopGTFSID: 'vic:rail:CFD',
        arrivalTime: '23:36',
        arrivalTimeMinutes: 1416,
        departureTime: '23:36',
        departureTimeMinutes: 1416,
        stopConditions: { pickup: 1, dropoff: 0 },
        stopDistance: 24525.56,
        platform: 'RRB'
      }
    ],
    origin: 'Dandenong Railway Station',
    departureTime: '22:40',
    destination: 'Caulfield Railway Station',
    destinationArrivalTime: '23:36',
    trueOrigin: 'Dandenong Railway Station',
    trueDestination: 'Caulfield Railway Station',
    trueDepartureTime: '22:40',
    trueDestinationArrivalTime: '23:36'
  },
  {
    mode: 'metro train',
    routeName: 'Cranbourne',
    routeNumber: null,
    routeGTFSID: '2-RRB',
    operationDays: [ '20251118', '20251119' ],
    calendarID: 'Tue - Wed / OC 25-103-1762852085905',
    tripID: 'Tue - Wed_8YT9s_rvKKO',
    shapeID: '278',
    block: 'NUL27',
    gtfsDirection: 1,
    direction: 'Up',
    runID: 'RRB-1FCCC3C7',
    isRailReplacementBus: true,
    isMTMRailTrip: true,
    stopTimings: [
      {
        stopName: 'Westall Railway Station',
        stopNumber: null,
        suburb: 'Clayton South',
        stopGTFSID: 'RAIL_WTL_Up',
        arrivalTime: '22:51',
        arrivalTimeMinutes: 1371,
        departureTime: '22:51',
        departureTimeMinutes: 1371,
        stopConditions: { pickup: 0, dropoff: 1 },
        stopDistance: 0
      },
      {
        stopName: 'Clayton Railway Station',
        stopNumber: null,
        suburb: 'Clayton',
        stopGTFSID: 'RAIL_CLA_Up',
        arrivalTime: '22:58',
        arrivalTimeMinutes: 1378,
        departureTime: '22:58',
        departureTimeMinutes: 1378,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 2.46
      },
      {
        stopName: 'Huntingdale Railway Station',
        stopNumber: null,
        suburb: 'Oakleigh',
        stopGTFSID: 'RAIL_HUN_Up',
        arrivalTime: '23:07',
        arrivalTimeMinutes: 1387,
        departureTime: '23:07',
        departureTimeMinutes: 1387,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 5.4415
      },
      {
        stopName: 'Oakleigh Railway Station',
        stopNumber: null,
        suburb: 'Oakleigh',
        stopGTFSID: 'RAIL_OAK_Up',
        arrivalTime: '23:17',
        arrivalTimeMinutes: 1397,
        departureTime: '23:17',
        departureTimeMinutes: 1397,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 8.8042
      },
      {
        stopName: 'Hughesdale Railway Station',
        stopNumber: null,
        suburb: 'Murrumbeena',
        stopGTFSID: 'RAIL_HUG_Up',
        arrivalTime: '23:23',
        arrivalTimeMinutes: 1403,
        departureTime: '23:23',
        departureTimeMinutes: 1403,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 10.6413
      },
      {
        stopName: 'Murrumbeena Railway Station',
        stopNumber: null,
        suburb: 'Murrumbeena',
        stopGTFSID: 'RAIL_MRB_Up',
        arrivalTime: '23:26',
        arrivalTimeMinutes: 1406,
        departureTime: '23:26',
        departureTimeMinutes: 1406,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 11.8948
      },
      {
        stopName: 'Carnegie Railway Station',
        stopNumber: null,
        suburb: 'Carnegie',
        stopGTFSID: 'RAIL_CNE_Up',
        arrivalTime: '23:30',
        arrivalTimeMinutes: 1410,
        departureTime: '23:30',
        departureTimeMinutes: 1410,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 13.2079
      },
      {
        stopName: 'Caulfield Railway Station',
        stopNumber: null,
        suburb: 'Caulfield East',
        stopGTFSID: 'RAIL_CFD_Up2',
        arrivalTime: '23:36',
        arrivalTimeMinutes: 1416,
        departureTime: '23:36',
        departureTimeMinutes: 1416,
        stopConditions: { pickup: 1, dropoff: 0 },
        stopDistance: 15.1368
      }
    ],
    origin: 'Westall Railway Station',
    departureTime: '22:51',
    destination: 'Caulfield Railway Station',
    destinationArrivalTime: '23:36',
    headsign: 'S'
  },
  {
    mode: 'metro train',
    routeName: 'Cranbourne',
    routeNumber: null,
    routeGTFSID: '2-RRB',
    operationDays: [ '20251118', '20251119' ],
    calendarID: 'Tue - Wed / OC 25-103-1762852085905',
    tripID: 'Tue - Wed_Q-taH0f2fNr',
    shapeID: '280',
    block: 'DON21',
    gtfsDirection: 0,
    direction: 'Down',
    runID: 'RRB-3BCC897A',
    isRailReplacementBus: true,
    isMTMRailTrip: true,
    stopTimings: [
      {
        stopName: 'Caulfield Railway Station',
        stopNumber: null,
        suburb: 'Caulfield East',
        stopGTFSID: 'RAIL_CFD_Down1',
        arrivalTime: '22:51',
        arrivalTimeMinutes: 1371,
        departureTime: '22:51',
        departureTimeMinutes: 1371,
        stopConditions: { pickup: 0, dropoff: 1 },
        stopDistance: 0
      },
      {
        stopName: 'Huntingdale Railway Station',
        stopNumber: null,
        suburb: 'Oakleigh',
        stopGTFSID: 'RAIL_HUN_Down',
        arrivalTime: '23:11',
        arrivalTimeMinutes: 1391,
        departureTime: '23:11',
        departureTimeMinutes: 1391,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 8.6768
      },
      {
        stopName: 'Clayton Railway Station',
        stopNumber: null,
        suburb: 'Clayton',
        stopGTFSID: 'RAIL_CLA_Down',
        arrivalTime: '23:18',
        arrivalTimeMinutes: 1398,
        departureTime: '23:18',
        departureTimeMinutes: 1398,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 11.7428
      },
      {
        stopName: 'Westall Railway Station',
        stopNumber: null,
        suburb: 'Clayton South',
        stopGTFSID: 'RAIL_WTL_Down',
        arrivalTime: '23:23',
        arrivalTimeMinutes: 1403,
        departureTime: '23:23',
        departureTimeMinutes: 1403,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 14.1256
      },
      {
        stopName: 'Springvale Railway Station',
        stopNumber: null,
        suburb: 'Springvale',
        stopGTFSID: 'RAIL_SPG_Down',
        arrivalTime: '23:30',
        arrivalTimeMinutes: 1410,
        departureTime: '23:30',
        departureTimeMinutes: 1410,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 17.1233
      },
      {
        stopName: 'Sandown Park Railway Station',
        stopNumber: null,
        suburb: 'Springvale',
        stopGTFSID: 'RAIL_SNP_Down',
        arrivalTime: '23:33',
        arrivalTimeMinutes: 1413,
        departureTime: '23:33',
        departureTimeMinutes: 1413,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 18.2841
      },
      {
        stopName: 'Noble Park Railway Station',
        stopNumber: null,
        suburb: 'Noble Park',
        stopGTFSID: 'RAIL_NPK_Down1',
        arrivalTime: '23:36',
        arrivalTimeMinutes: 1416,
        departureTime: '23:36',
        departureTimeMinutes: 1416,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 19.8396
      },
      {
        stopName: 'Yarraman Railway Station',
        stopNumber: null,
        suburb: 'Noble Park',
        stopGTFSID: 'RAIL_YMN_Down',
        arrivalTime: '23:41',
        arrivalTimeMinutes: 1421,
        departureTime: '23:41',
        departureTimeMinutes: 1421,
        stopConditions: { pickup: 0, dropoff: 0 },
        stopDistance: 21.9668
      },
      {
        stopName: 'Dandenong Railway Station',
        stopNumber: null,
        suburb: 'Dandenong',
        stopGTFSID: 'RAIL_DNG_Down1',
        arrivalTime: '23:46',
        arrivalTimeMinutes: 1426,
        departureTime: '23:46',
        departureTimeMinutes: 1426,
        stopConditions: { pickup: 1, dropoff: 0 },
        stopDistance: 24.1488
      }
    ],
    origin: 'Caulfield Railway Station',
    departureTime: '22:51',
    destination: 'Dandenong Railway Station',
    destinationArrivalTime: '23:46',
    headsign: 'L1'
  }
]