#!/bin/bash
cd /home/ec2-user/TransportVic

# Note: we do not want sudo or we cannot kill the process
NODE_ENV=prod node --max-old-space-size=4096 /home/ec2-user/TransportVic/index.js >> /home/ec2-user/log 2>> /home/ec2-user/err
