#!/bin/bash
cd /home/ec2-user/TransportVic

/home/ec2-user/.nvm/versions/node/v14.9.0/bin/node --max-old-space-size=4096 /home/ec2-user/TransportVic/index.js >> /home/ec2-user/log 2>> /home/ec2-user/err
