#!/bin/bash
cd /home/ec2-user/TransportVic

sudo /home/ec2-user/.nvm/versions/node/v15.0.1/bin/node --max-old-space-size=4096 /home/ec2-user/TransportVic/index.js >> /home/ec2-user/log 2>> /home/ec2-user/err
