export default [{
  stopName: 'Caulfield Railway Station',
  suburb: [ 'Caulfield East' ],
  cleanSuburbs: [ 'caulfield-east' ],
  bays: [
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'station',
      parentStopGTFSID: null,
      vnetStationName: 'Caulfield'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '22248',
      location: { type: 'Point', coordinates: [ 145.04251962, -37.87722507 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14251',
      location: { type: 'Point', coordinates: [ 145.04208396, -37.87736201 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '1'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14252',
      location: { type: 'Point', coordinates: [ 145.04231148, -37.87735678 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '2'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14253',
      location: { type: 'Point', coordinates: [ 145.04238158, -37.87728586 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '3'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14254',
      location: { type: 'Point', coordinates: [ 145.04243037, -37.8771605 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '4'
    },
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '26135',
      location: { type: 'Point', coordinates: [ 145.04199844, -37.87758588 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: 'RRB'
    },
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'station',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Railway Station/Derby Rd #57',
      fullStopName: 'Caulfield Railway Station/Derby Road',
      stopGTFSID: '18457',
      location: { type: 'Point', coordinates: [ 145.04193878, -37.87640435 ] },
      stopNumber: '57',
      mode: 'tram',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null,
      tramTrackerID: '1089',
      tramTrackerName: 'Caulfield Railway Station & Derby Road',
      levelAccess: false
    },
    {
      originalName: 'Caulfield Railway Station/Derby Rd #57',
      fullStopName: 'Caulfield Railway Station/Derby Road',
      stopGTFSID: '18651',
      location: { type: 'Point', coordinates: [ 145.0416774, -37.8764 ] },
      stopNumber: '57',
      mode: 'tram',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null,
      tramTrackerID: '2089',
      tramTrackerName: 'Caulfield Railway Station & Derby Road',
      levelAccess: false
    },
    {
      originalName: 'Caulfield Station/Normanby Rd',
      fullStopName: 'Caulfield Railway Station/Normanby Road',
      stopGTFSID: '14907',
      location: { type: 'Point', coordinates: [ 145.04201124, -37.87753202 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '20583',
      location: { type: 'Point', coordinates: [ 145.04232245, -37.87694242 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Railway Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '22022',
      location: { type: 'Point', coordinates: [ 145.04315316, -37.87734375 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '52537',
      location: { type: 'Point', coordinates: [ 145.04232245, -37.87694242 ] },
      stopNumber: null,
      mode: 'regional coach',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    }
  ],
  mergeName: 'Caulfield Railway Station',
  services: [],
  screenServices: [],
  cleanName: 'caulfield-railway-station'
},
{
  stopName: 'Flinders Street Railway Station',
  suburb: [ 'Melbourne' ],
  cleanSuburbs: [ 'melbourne' ],
  bays: [
    {
      originalName: 'Flinders Street Railway Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: 'vic:rail:FSS',
      location: { type: 'Point', coordinates: [ 144.96696435, -37.81830513 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Melbourne',
      stopType: 'station',
      parentStopGTFSID: null,
      vnetStationName: 'Melbourne: Flinders Street'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '22238',
      location: { type: 'Point', coordinates: [ 144.96696435, -37.81830513 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11212',
      location: { type: 'Point', coordinates: [ 144.96483434, -37.81851165 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '1'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11213',
      location: { type: 'Point', coordinates: [ 144.96601006, -37.81830668 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '2'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11214',
      location: { type: 'Point', coordinates: [ 144.96646672, -37.81822445 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '3'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11215',
      location: { type: 'Point', coordinates: [ 144.96655582, -37.81828907 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '4'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11216',
      location: { type: 'Point', coordinates: [ 144.96660025, -37.81832588 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '5'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11217',
      location: { type: 'Point', coordinates: [ 144.9669283, -37.81837661 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '6'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '11218',
      location: { type: 'Point', coordinates: [ 144.96674342, -37.81849057 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '7'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '12201',
      location: { type: 'Point', coordinates: [ 144.96826668, -37.81845378 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '13'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '12202',
      location: { type: 'Point', coordinates: [ 144.96817708, -37.81840717 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '12'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '12203',
      location: { type: 'Point', coordinates: [ 144.96619788, -37.81891371 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '10'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '12204',
      location: { type: 'Point', coordinates: [ 144.96687671, -37.81860101 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '9'
    },
    {
      originalName: 'Flinders Street Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '12205',
      location: { type: 'Point', coordinates: [ 144.9668893, -37.81855617 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: '8'
    },
    {
      originalName: 'Flinders Street Railway Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: '26170',
      location: { type: 'Point', coordinates: [ 144.96591676, -37.81798064 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FSS',
      platform: 'RRB'
    },
    {
      originalName: 'Flinders Street Railway Station',
      fullStopName: 'Flinders Street Railway Station',
      stopGTFSID: 'vic:rail:FSS',
      location: { type: 'Point', coordinates: [ 144.96696435, -37.81830513 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Melbourne',
      stopType: 'station',
      parentStopGTFSID: null
    },
    {
      originalName: 'Flinders Street Railway Station/Elizabeth St #1',
      fullStopName: 'Flinders Street Railway Station/Elizabeth Street',
      stopGTFSID: '17850',
      location: { type: 'Point', coordinates: [ 144.96476527, -37.81771743 ] },
      stopNumber: '1',
      mode: 'tram',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: null,
      tramTrackerID: '3801',
      tramTrackerName: 'Flinders Street Railway Station',
      levelAccess: false
    },
    {
      originalName: 'Flinders Street Railway Station/Elizabeth St #1',
      fullStopName: 'Flinders Street Railway Station/Elizabeth Street',
      stopGTFSID: '17877',
      location: { type: 'Point', coordinates: [ 144.9648398, -37.81789895 ] },
      stopNumber: '1',
      mode: 'tram',
      suburb: 'Melbourne',
      stopType: 'stop',
      parentStopGTFSID: null,
      tramTrackerID: '8007',
      tramTrackerName: 'Flinders Street Railway Station',
      levelAccess: false
    }
  ],
  mergeName: 'Flinders Street Railway Station',
  services: [],
  screenServices: [],
  cleanName: 'flinders-street-railway-station'
},
{
  stopName: 'Frankston Railway Station',
  suburb: [ 'Frankston' ],
  cleanSuburbs: [ 'frankston' ],
  bays: [
    {
      originalName: 'Frankston Railway Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: 'vic:rail:FKN',
      location: { type: 'Point', coordinates: [ 145.12616228, -38.14299007 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'station',
      parentStopGTFSID: null
    },
    {
      originalName: 'Frankston Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '11220',
      location: { type: 'Point', coordinates: [ 145.12604465, -38.1426818 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: '1'
    },
    {
      originalName: 'Frankston Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '11221',
      location: { type: 'Point', coordinates: [ 145.12619247, -38.14270218 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: '2'
    },
    {
      originalName: 'Frankston Railway Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '26172',
      location: { type: 'Point', coordinates: [ 145.12665884, -38.14320526 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: 'RRB'
    },
    {
      originalName: 'Frankston Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '26510',
      location: { type: 'Point', coordinates: [ 145.12621712, -38.14263048 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: '3'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21208',
      location: { type: 'Point', coordinates: [ 145.12551202, -38.14343026 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay B'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21209',
      location: { type: 'Point', coordinates: [ 145.12575374, -38.14290244 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay C'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21210',
      location: { type: 'Point', coordinates: [ 145.12582414, -38.1423809 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay H'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21212',
      location: { type: 'Point', coordinates: [ 145.12594592, -38.14252703 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay E'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21213',
      location: { type: 'Point', coordinates: [ 145.12584983, -38.14271473 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay D'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21214',
      location: { type: 'Point', coordinates: [ 145.1261495, -38.14215179 ] },
      stopNumber: '125',
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay F'
    },
    {
      originalName: 'Frankston Railway Station/Fletcher Rd',
      fullStopName: 'Frankston Railway Station/Fletcher Road',
      stopGTFSID: '21215',
      location: { type: 'Point', coordinates: [ 145.12622472, -38.1441175 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay J'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21216',
      location: { type: 'Point', coordinates: [ 145.12572805, -38.14256861 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay G'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21217',
      location: { type: 'Point', coordinates: [ 145.12442553, -38.14486377 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay K'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21218',
      location: { type: 'Point', coordinates: [ 145.12591977, -38.14221121 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay I'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '40396',
      location: { type: 'Point', coordinates: [ 145.12534242, -38.14381505 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay A'
    }
  ],
  mergeName: 'Frankston Railway Station',
  services: [],
  screenServices: [],
  cleanName: 'frankston-railway-station'
}]