export default [{
  stopName: 'Caulfield Railway Station',
  suburb: [ 'Caulfield East' ],
  cleanSuburbs: [ 'caulfield-east' ],
  bays: [
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'station',
      parentStopGTFSID: null,
      vnetStationName: 'Caulfield'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '22248',
      location: { type: 'Point', coordinates: [ 145.04251962, -37.87722507 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14251',
      location: { type: 'Point', coordinates: [ 145.04208396, -37.87736201 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '1'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14252',
      location: { type: 'Point', coordinates: [ 145.04231148, -37.87735678 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '2'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14253',
      location: { type: 'Point', coordinates: [ 145.04238158, -37.87728586 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '3'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14254',
      location: { type: 'Point', coordinates: [ 145.04243037, -37.8771605 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '4'
    },
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '26135',
      location: { type: 'Point', coordinates: [ 145.04199844, -37.87758588 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: 'RRB'
    },
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'station',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Railway Station/Derby Rd #57',
      fullStopName: 'Caulfield Railway Station/Derby Road',
      stopGTFSID: '18457',
      location: { type: 'Point', coordinates: [ 145.04193878, -37.87640435 ] },
      stopNumber: '57',
      mode: 'tram',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null,
      tramTrackerID: '1089',
      tramTrackerName: 'Caulfield Railway Station & Derby Road',
      levelAccess: false
    },
    {
      originalName: 'Caulfield Railway Station/Derby Rd #57',
      fullStopName: 'Caulfield Railway Station/Derby Road',
      stopGTFSID: '18651',
      location: { type: 'Point', coordinates: [ 145.0416774, -37.8764 ] },
      stopNumber: '57',
      mode: 'tram',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null,
      tramTrackerID: '2089',
      tramTrackerName: 'Caulfield Railway Station & Derby Road',
      levelAccess: false
    },
    {
      originalName: 'Caulfield Station/Normanby Rd',
      fullStopName: 'Caulfield Railway Station/Normanby Road',
      stopGTFSID: '14907',
      location: { type: 'Point', coordinates: [ 145.04201124, -37.87753202 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '20583',
      location: { type: 'Point', coordinates: [ 145.04232245, -37.87694242 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Railway Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '22022',
      location: { type: 'Point', coordinates: [ 145.04315316, -37.87734375 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '52537',
      location: { type: 'Point', coordinates: [ 145.04232245, -37.87694242 ] },
      stopNumber: null,
      mode: 'regional coach',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    }
  ],
  mergeName: 'Caulfield Railway Station',
  services: [],
  screenServices: [],
  cleanName: 'caulfield-railway-station'
},
{
  stopName: 'Frankston Railway Station',
  suburb: [ 'Frankston' ],
  cleanSuburbs: [ 'frankston' ],
  bays: [
    {
      originalName: 'Frankston Railway Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: 'vic:rail:FKN',
      location: { type: 'Point', coordinates: [ 145.12616228, -38.14299007 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'station',
      parentStopGTFSID: null
    },
    {
      originalName: 'Frankston Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '11220',
      location: { type: 'Point', coordinates: [ 145.12604465, -38.1426818 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: '1'
    },
    {
      originalName: 'Frankston Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '11221',
      location: { type: 'Point', coordinates: [ 145.12619247, -38.14270218 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: '2'
    },
    {
      originalName: 'Frankston Railway Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '26172',
      location: { type: 'Point', coordinates: [ 145.12665884, -38.14320526 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: 'RRB'
    },
    {
      originalName: 'Frankston Station',
      fullStopName: 'Frankston Railway Station',
      stopGTFSID: '26510',
      location: { type: 'Point', coordinates: [ 145.12621712, -38.14263048 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:FKN',
      platform: '3'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21208',
      location: { type: 'Point', coordinates: [ 145.12551202, -38.14343026 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay B'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21209',
      location: { type: 'Point', coordinates: [ 145.12575374, -38.14290244 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay C'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21210',
      location: { type: 'Point', coordinates: [ 145.12582414, -38.1423809 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay H'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21212',
      location: { type: 'Point', coordinates: [ 145.12594592, -38.14252703 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay E'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21213',
      location: { type: 'Point', coordinates: [ 145.12584983, -38.14271473 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay D'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21214',
      location: { type: 'Point', coordinates: [ 145.1261495, -38.14215179 ] },
      stopNumber: '125',
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay F'
    },
    {
      originalName: 'Frankston Railway Station/Fletcher Rd',
      fullStopName: 'Frankston Railway Station/Fletcher Road',
      stopGTFSID: '21215',
      location: { type: 'Point', coordinates: [ 145.12622472, -38.1441175 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay J'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21216',
      location: { type: 'Point', coordinates: [ 145.12572805, -38.14256861 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay G'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21217',
      location: { type: 'Point', coordinates: [ 145.12442553, -38.14486377 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay K'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '21218',
      location: { type: 'Point', coordinates: [ 145.12591977, -38.14221121 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay I'
    },
    {
      originalName: 'Frankston Railway Station/Young St',
      fullStopName: 'Frankston Railway Station/Young Street',
      stopGTFSID: '40396',
      location: { type: 'Point', coordinates: [ 145.12534242, -38.14381505 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Frankston',
      stopType: 'stop',
      parentStopGTFSID: null,
      platform: 'Bay A'
    }
  ],
  mergeName: 'Frankston Railway Station',
  services: [],
  screenServices: [],
  cleanName: 'frankston-railway-station'
}]