module.exports = [
  'caroline-springs/caroline-springs-library-caroline-springs-boulevard',
  'sydenham/watergardens-railway-station',
  'hillside-3037/parkwood-green-primary-school-gourlay-road',
  'sydenham/aqua-gardens-shopping-centre-kings-road',
  'deer-park/deer-park-railway-station',
  'deer-park/brimbank-central-shopping-centre-neale-road',
  'taylors-lakes/taylors-lakes-shopping-centre-melton-highway',
  'sunshine/sunshine-plaza-shopping-centre-harvester-road',
  'sunshine-north/munro-avenue-mcintyre-road',
  'maidstone/churchill-avenue-ballarat-road',
  'footscray/barkly-street-victoria-street',
  'keilor-east/milleara-shopping-centre',
  'maribyrnong/highpoint-shopping-centre',
  'footscray/commercial-road-ballarat-road',
  'west-footscray/west-footscray-railway-station',
  'altona-north/altona-gate-shopping-centre',
  'newport/oxford-street-mason-street',

  'werribee/werribee-sports-centre-ballan-road',
  'manor-lakes/manor-lakes-central-shopping-centre',
  'tarneit/tarneit-central-shopping-centre-derrimut-road',
  'tarneit/wyndham-village-shopping-centre',
  'williams-landing/williams-landing-boulevard-palmers-road',
  'hoppers-crossing/werribee-village-shopping-centre',
  'tarneit/good-news-christian-school-tarneit-road',
  'tarneit/wilandra-drive-leakes-road',
  'point-cook/point-cook-shopping-centre-boardwalk-boulevard',
  'point-cook/sanctuary-lakes-shopping-centre-point-cook-road',

  'broadmeadows/cobram-street-pascoe-vale-road',
  'meadow-heights/meadow-heights-shopping-centre-hudson-circuit',
  'craigieburn/gillingham-crescent-bridgewater-road',
  'westmeadows/north-circular-road-broadmeadows-road',
  'essendon/essendon-north-primary-school-keilor-road',
  'fawkner/pascoe-vale-north-primary-school',
  'brunswick-west/hope-street-melville-road',

  'melbourne-city/melbourne-central-lonsdale-street',
  'melbourne-city/little-bourke-street-queen-street',

  'heidelberg-west/the-mall-oriel-road',
  'northcote/westgarth-railway-station',
  'kew/yarra-bend-park-studley-park-road',
  'doncaster/doncaster-park-ride-doncaster-road',
  'abbotsford/victoria-park-railway-station',
  'abbotsford/langridge-street-hoddle-street',
  'templestowe/templestowe-bowling-club-swilk-street',
  'templestowe-lower/manningham-road-high-street',
  'mitcham/harrison-street-mitcham-road',

  'glen-waverley/syndal-railway-station',
  'blackburn/canterbury-road-main-street',
  'brighton/gardenvale-railway-station',
  'oakleigh/huntingdale-railway-station',
  'mulgrave/brandon-park-drive-wellington-road',
  'dandenong/chisholm-tafe-dandenong-stud-road',
  'dandenong/dandenong-railway-station',
  'springvale-south/athol-road-primary-school-athol-road',
  'clayton/clayton-shopping-centre-clayton-road',
  'mulgrave/wellington-secondary-college-police-road',
  'bentleigh/bentleigh-railway-station',
  'clayton/monash-university-bus-loop',

  'narre-warren/fountain-gate-shopping-centre-overland-drive',
  'narre-warren-south/casey-central-shopping-centre',
  'cranbourne-west/duff-street-evans-road',
  'hallam/hallam-railway-station',

  'rosebud/rosebud-village-shopping-centre-point-nepean-road',
  'mount-eliza/mount-eliza-shopping-centre-mount-eliza-way',
  'portsea/point-nepean-road-franklin-road',
  'sandhurst/sandarra-boulevard-mccormicks-road',
  'frankston-north/mahogany-rise-primary-school-monterey-boulevard',

  'oakleigh-east/huntingdale-road-ferntree-gully-road',
  'notting-hill/blackburn-road-ferntree-gully-road',
  'wantirna/knox-city-shopping-centre',
  'vermont-south/vermont-south-tram-terminus-burwood-highway',
  'bayswater/bayswater-railway-station',
  'croydon/croydon-railway-station',
  'chirnside-park/chirnside-park-shopping-centre-maroondah-highway',
  'ringwood/burnt-bridge-shopping-centre-maroondah-highway',
  'yarra-glen/melba-highway-armstrong-grove',
  'mount-evelyn/olinda-creek-trail-swansea-road',
  'lilydale/lilydale-railway-station',

  'south-morang/south-morang-railway-station',
  'mernda/mernda-railway-station',
  'epping/epping-plaza-shopping-centre-cooper-street',
  'thomastown/thomastown-railway-station'
]
