export default {
  mode: 'regional train',
  routeName: 'Traralgon',
  routeNumber: null,
  routeGTFSID: '1-TRN',
  operationDays: [ '20250904', '20250905' ],
  tripID: '01-TRN--7-T0-8457',
  shapeID: '1-TRN-mjp-7.1.H',
  block: null,
  gtfsDirection: 0,
  runID: '8457',
  isRailReplacementBus: false,
  direction: 'Down',
  stopTimings: [
    {
      stopName: 'East Pakenham Railway Station',
      stopNumber: null,
      suburb: 'Pakenham',
      stopGTFSID: 'vic:rail:EPH',
      arrivalTime: null,
      arrivalTimeMinutes: null,
      departureTime: '00:32',
      departureTimeMinutes: 1472,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: '0.00'
    },
    {
      stopName: 'Nar Nar Goon Railway Station',
      stopNumber: null,
      suburb: 'Nar Nar Goon',
      stopGTFSID: 'vic:rail:NNG',
      arrivalTime: '00:37',
      arrivalTimeMinutes: 1477,
      departureTime: '00:37',
      departureTimeMinutes: 1477,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '5759.92'
    },
    {
      stopName: 'Tynong Railway Station',
      stopNumber: null,
      suburb: 'Tynong',
      stopGTFSID: 'vic:rail:TYN',
      arrivalTime: '00:41',
      arrivalTimeMinutes: 1481,
      departureTime: '00:41',
      departureTimeMinutes: 1481,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '10734.22'
    },
    {
      stopName: 'Garfield Railway Station',
      stopNumber: null,
      suburb: 'Garfield',
      stopGTFSID: 'vic:rail:GAR-V',
      arrivalTime: '00:45',
      arrivalTimeMinutes: 1485,
      departureTime: '00:45',
      departureTimeMinutes: 1485,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '14820.08'
    },
    {
      stopName: 'Bunyip Railway Station',
      stopNumber: null,
      suburb: 'Bunyip',
      stopGTFSID: 'vic:rail:BYP',
      arrivalTime: '00:49',
      arrivalTimeMinutes: 1489,
      departureTime: '00:49',
      departureTimeMinutes: 1489,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '19014.64'
    },
    {
      stopName: 'Longwarry Railway Station',
      stopNumber: null,
      suburb: 'Longwarry',
      stopGTFSID: 'vic:rail:LWY',
      arrivalTime: '00:53',
      arrivalTimeMinutes: 1493,
      departureTime: '00:53',
      departureTimeMinutes: 1493,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '23355.71'
    },
    {
      stopName: 'Drouin Railway Station',
      stopNumber: null,
      suburb: 'Drouin',
      stopGTFSID: 'vic:rail:DRN',
      arrivalTime: '00:59',
      arrivalTimeMinutes: 1499,
      departureTime: '00:59',
      departureTimeMinutes: 1499,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '32053.33'
    },
    {
      stopName: 'Warragul Railway Station',
      stopNumber: null,
      suburb: 'Warragul',
      stopGTFSID: 'vic:rail:WGL',
      arrivalTime: '01:05',
      arrivalTimeMinutes: 1505,
      departureTime: '01:05',
      departureTimeMinutes: 1505,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '39678.81'
    },
    {
      stopName: 'Yarragon Railway Station',
      stopNumber: null,
      suburb: 'Yarragon',
      stopGTFSID: 'vic:rail:YON',
      arrivalTime: '01:13',
      arrivalTimeMinutes: 1513,
      departureTime: '01:13',
      departureTimeMinutes: 1513,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '52018.43'
    },
    {
      stopName: 'Trafalgar Railway Station',
      stopNumber: null,
      suburb: 'Trafalgar',
      stopGTFSID: 'vic:rail:TAR',
      arrivalTime: '01:18',
      arrivalTimeMinutes: 1518,
      departureTime: '01:18',
      departureTimeMinutes: 1518,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '60090.42'
    },
    {
      stopName: 'Moe Railway Station',
      stopNumber: null,
      suburb: 'Moe',
      stopGTFSID: 'vic:rail:MOE',
      arrivalTime: '01:24',
      arrivalTimeMinutes: 1524,
      departureTime: '01:24',
      departureTimeMinutes: 1524,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '70006.30'
    },
    {
      stopName: 'Morwell Railway Station',
      stopNumber: null,
      suburb: 'Morwell',
      stopGTFSID: 'vic:rail:MWL',
      arrivalTime: '01:34',
      arrivalTimeMinutes: 1534,
      departureTime: '01:34',
      departureTimeMinutes: 1534,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '84627.98'
    },
    {
      stopName: 'Traralgon Railway Station',
      stopNumber: null,
      suburb: 'Traralgon',
      stopGTFSID: 'vic:rail:TRN',
      arrivalTime: '01:46',
      arrivalTimeMinutes: 1546,
      departureTime: null,
      departureTimeMinutes: null,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: '98342.31'
    }
  ],
  origin: 'East Pakenham Railway Station',
  departureTime: '24:32',
  destination: 'Traralgon Railway Station',
  destinationArrivalTime: '25:46'
}