module.exports = [
  'Richmond',
  'South Yarra',
  'Burnley',
  'Gardenvale',
  'Brighton Beach',
  'Middle Brighton',
  'Balaclava',
  'Murrumbeena',
  'Huntingdale',
  'Noble Park',
  'Lynbrook',
  'Berwick',
  'McKinnon',
  'Southland',
  'Bonbeach',
  'Tooronga',
  'Jordanville',
  'Ashburton',
  'Riversdale',
  'Glenferrie',
  'Surrey Hills',
  'Box Hill',
  'Blackburn',
  'Mitcham',
  'Croydon',
  'Ferntree Gully',
  'North Richmond',
  'Croxton',
  'Regent',
  'Keon Park',
  'Hawkstowe',
  'Ivanhoe',
  'Macleod',
  'Montmorency',
  'Wattle Glen',
  'Royal Park',
  'North Melbourne',
  'Ascot Vale',
  'Pascoe Vale',
  'Roxburgh Park',
  'West Footscray',
  'Ginifer',
  'Diggers Rest',
  'Yarraville',
  'Williamstown Beach',
  'North Williamstown',
  'Altona',
  'Williams Landing',
  'Melbourne Central',
  'Flinders Street',
  'Southern Cross',
  'Parliament',
  'Kooyong',
  'Springvale',
  'Camberwell',
  'Caulfield',
  'Footscray',
  'Sunshine',
  'Laverton',
  'Newport',
  'Essendon',
  'Reservoir',
  'Epping',
  'Clifton Hill',
  'Boronia',
  'Eaglemont',
  'Cardinia Road',
  'Hampton'
]
