export default {
  mode: 'metro train',
  routeName: 'Alamein',
  routeNumber: null,
  routeGTFSID: '2-ALM',
  operationDays: [ '20260207', '20260214', '20260221', '20260228', '20260307' ],
  calendarID: 'T2_3',
  tripID: '02-ALM--1-T2-2302',
  shapeID: '2-ALM-vpt-1.1.R',
  block: null,
  gtfsDirection: 1,
  runID: '2302',
  isRailReplacementBus: false,
  direction: 'Up',
  stopTimings: [
    {
      stopName: 'Alamein Railway Station',
      stopNumber: null,
      suburb: 'Ashburton',
      stopGTFSID: 'vic:rail:ALM',
      arrivalTime: '04:57',
      arrivalTimeMinutes: 297,
      departureTime: '04:57',
      departureTimeMinutes: 297,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0,
      platform: '1'
    },
    {
      stopName: 'Ashburton Railway Station',
      stopNumber: null,
      suburb: 'Ashburton',
      stopGTFSID: 'vic:rail:ASH',
      arrivalTime: '04:58',
      arrivalTimeMinutes: 298,
      departureTime: '04:58',
      departureTimeMinutes: 298,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 713.74,
      platform: '1'
    },
    {
      stopName: 'Burwood Railway Station',
      stopNumber: null,
      suburb: 'Glen Iris',
      stopGTFSID: 'vic:rail:BWD',
      arrivalTime: '05:00',
      arrivalTimeMinutes: 300,
      departureTime: '05:00',
      departureTimeMinutes: 300,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 1940.63,
      platform: '1'
    },
    {
      stopName: 'Hartwell Railway Station',
      stopNumber: null,
      suburb: 'Camberwell',
      stopGTFSID: 'vic:rail:HWL',
      arrivalTime: '05:02',
      arrivalTimeMinutes: 302,
      departureTime: '05:02',
      departureTimeMinutes: 302,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 2901.39,
      platform: '1'
    },
    {
      stopName: 'Willison Railway Station',
      stopNumber: null,
      suburb: 'Camberwell',
      stopGTFSID: 'vic:rail:WSN',
      arrivalTime: '05:04',
      arrivalTimeMinutes: 304,
      departureTime: '05:04',
      departureTimeMinutes: 304,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 3921.94,
      platform: '1'
    },
    {
      stopName: 'Riversdale Railway Station',
      stopNumber: null,
      suburb: 'Camberwell',
      stopGTFSID: 'vic:rail:RIV',
      arrivalTime: '05:05',
      arrivalTimeMinutes: 305,
      departureTime: '05:05',
      departureTimeMinutes: 305,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 4426.33,
      platform: '1'
    },
    {
      stopName: 'Camberwell Railway Station',
      stopNumber: null,
      suburb: 'Camberwell',
      stopGTFSID: 'vic:rail:CAM',
      arrivalTime: '05:08',
      arrivalTimeMinutes: 308,
      departureTime: '05:08',
      departureTimeMinutes: 308,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 5933.94,
      platform: '2'
    }
  ],
  origin: 'Alamein Railway Station',
  departureTime: '04:57',
  destination: 'Camberwell Railway Station',
  destinationArrivalTime: '05:08',
  trueOrigin: 'Alamein Railway Station',
  trueDestination: 'Camberwell Railway Station',
  trueDepartureTime: '04:57',
  trueDestinationArrivalTime: '05:08'
}