export default [{
  mode: 'regional train',
  routeName: 'Albury',
  routeNumber: null,
  routeGTFSID: '1-ABY',
  operationDays: [ '20251214' ],
  calendarID: 'T3_1',
  tripID: '01-ABY--10-T3-8605',
  shapeID: '1-ABY-mjp-10.1.H',
  block: null,
  gtfsDirection: 0,
  runID: '8605',
  isRailReplacementBus: false,
  direction: 'Down',
  stopTimings: [
    {
      stopName: 'Southern Cross Railway Station',
      stopNumber: null,
      suburb: 'Docklands',
      stopGTFSID: 'vic:rail:SSS',
      arrivalTime: '07:07',
      arrivalTimeMinutes: 427,
      departureTime: '07:07',
      departureTimeMinutes: 427,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0
    },
    {
      stopName: 'Broadmeadows Railway Station',
      stopNumber: null,
      suburb: 'Broadmeadows',
      stopGTFSID: 'vic:rail:BMS',
      arrivalTime: '07:35',
      arrivalTimeMinutes: 455,
      departureTime: '07:35',
      departureTimeMinutes: 455,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 27298.99
    },
    {
      stopName: 'Seymour Railway Station',
      stopNumber: null,
      suburb: 'Seymour',
      stopGTFSID: 'vic:rail:SER',
      arrivalTime: '08:24',
      arrivalTimeMinutes: 504,
      departureTime: '08:26',
      departureTimeMinutes: 506,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 109304.93
    },
    {
      stopName: 'Albury Railway Station',
      stopNumber: null,
      suburb: 'Albury (NSW)',
      stopGTFSID: 'nsw:rail:ABY',
      arrivalTime: '10:43',
      arrivalTimeMinutes: 643,
      departureTime: '10:43',
      departureTimeMinutes: 643,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 316035.38
    }
  ],
  origin: 'Southern Cross Railway Station',
  departureTime: '07:07',
  destination: 'Albury Railway Station',
  destinationArrivalTime: '10:43'
}, {
  mode: 'regional train',
  routeName: 'Albury',
  routeNumber: null,
  routeGTFSID: '1-ABY',
  operationDays: [ '20251208', '20251209' ],
  calendarID: 'T0_2',
  tripID: '01-ABY--6-T0-8605',
  shapeID: '1-ABY-mjp-6.1.H',
  block: null,
  gtfsDirection: 0,
  runID: '8605',
  isRailReplacementBus: false,
  direction: 'Down',
  stopTimings: [
    {
      stopName: 'Southern Cross Railway Station',
      stopNumber: null,
      suburb: 'Docklands',
      stopGTFSID: 'vic:rail:SSS',
      arrivalTime: '07:07',
      arrivalTimeMinutes: 427,
      departureTime: '07:07',
      departureTimeMinutes: 427,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0
    },
    {
      stopName: 'Broadmeadows Railway Station',
      stopNumber: null,
      suburb: 'Broadmeadows',
      stopGTFSID: 'vic:rail:BMS',
      arrivalTime: '07:35',
      arrivalTimeMinutes: 455,
      departureTime: '07:35',
      departureTimeMinutes: 455,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 27298.99
    },
    {
      stopName: 'Seymour Railway Station',
      stopNumber: null,
      suburb: 'Seymour',
      stopGTFSID: 'vic:rail:SER',
      arrivalTime: '08:24',
      arrivalTimeMinutes: 504,
      departureTime: '08:26',
      departureTimeMinutes: 506,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 109304.93
    },
    {
      stopName: 'Albury Railway Station',
      stopNumber: null,
      suburb: 'Albury (NSW)',
      stopGTFSID: 'nsw:rail:ABY',
      arrivalTime: '10:43',
      arrivalTimeMinutes: 643,
      departureTime: '10:43',
      departureTimeMinutes: 643,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 316035.38
    }
  ],
  origin: 'Southern Cross Railway Station',
  departureTime: '07:07',
  destination: 'Albury Railway Station',
  destinationArrivalTime: '10:43'
}]