export default [{
  mode: 'regional train',
  routeName: 'Albury',
  routeNumber: null,
  routeGTFSID: '1-ABY',
  operationDays: [ '20251214' ],
  calendarID: 'T3_1',
  tripID: '01-ABY--10-T3-8605',
  shapeID: '1-ABY-mjp-10.1.H',
  block: null,
  gtfsDirection: 0,
  runID: '8605',
  isRailReplacementBus: false,
  direction: 'Down',
  stopTimings: [
    {
      stopName: 'Southern Cross Railway Station',
      stopNumber: null,
      suburb: 'Docklands',
      stopGTFSID: 'vic:rail:SSS',
      arrivalTime: '07:07',
      arrivalTimeMinutes: 427,
      departureTime: '07:07',
      departureTimeMinutes: 427,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0
    },
    {
      stopName: 'Broadmeadows Railway Station',
      stopNumber: null,
      suburb: 'Broadmeadows',
      stopGTFSID: 'vic:rail:BMS',
      arrivalTime: '07:35',
      arrivalTimeMinutes: 455,
      departureTime: '07:35',
      departureTimeMinutes: 455,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 27298.99
    },
    {
      stopName: 'Seymour Railway Station',
      stopNumber: null,
      suburb: 'Seymour',
      stopGTFSID: 'vic:rail:SER',
      arrivalTime: '08:24',
      arrivalTimeMinutes: 504,
      departureTime: '08:26',
      departureTimeMinutes: 506,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 109304.93
    },
    {
      stopName: 'Avenel Railway Station',
      stopNumber: null,
      suburb: 'Avenel',
      stopGTFSID: 'vic:rail:AVL',
      arrivalTime: '08:37',
      arrivalTimeMinutes: 517,
      departureTime: '08:37',
      departureTimeMinutes: 517,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 126589.8
    },
    {
      stopName: 'Euroa Railway Station',
      stopNumber: null,
      suburb: 'Euroa',
      stopGTFSID: 'vic:rail:EOA',
      arrivalTime: '08:56',
      arrivalTimeMinutes: 536,
      departureTime: '08:56',
      departureTimeMinutes: 536,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 161618.19
    },
    {
      stopName: 'Violet Town Railway Station',
      stopNumber: null,
      suburb: 'Violet Town',
      stopGTFSID: 'vic:rail:VTN',
      arrivalTime: '09:07',
      arrivalTimeMinutes: 547,
      departureTime: '09:07',
      departureTimeMinutes: 547,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 179810.33
    },
    {
      stopName: 'Benalla Railway Station',
      stopNumber: null,
      suburb: 'Benalla',
      stopGTFSID: 'vic:rail:BXA',
      arrivalTime: '09:22',
      arrivalTimeMinutes: 562,
      departureTime: '09:24',
      departureTimeMinutes: 564,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 205933.09
    },
    {
      stopName: 'Wangaratta Railway Station',
      stopNumber: null,
      suburb: 'Wangaratta',
      stopGTFSID: 'vic:rail:WRT',
      arrivalTime: '09:47',
      arrivalTimeMinutes: 587,
      departureTime: '09:49',
      departureTimeMinutes: 589,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 244660.43
    },
    {
      stopName: 'Springhurst Railway Station',
      stopNumber: null,
      suburb: 'Springhurst',
      stopGTFSID: 'vic:rail:SHT',
      arrivalTime: '10:02',
      arrivalTimeMinutes: 602,
      departureTime: '10:02',
      departureTimeMinutes: 602,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 268445.71
    },
    {
      stopName: 'Chiltern Railway Station',
      stopNumber: null,
      suburb: 'Chiltern',
      stopGTFSID: 'vic:rail:CHI',
      arrivalTime: '10:10',
      arrivalTimeMinutes: 610,
      departureTime: '10:10',
      departureTimeMinutes: 610,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 282195.29
    },
    {
      stopName: 'Wodonga Railway Station',
      stopNumber: null,
      suburb: 'Wodonga',
      stopGTFSID: 'vic:rail:WOD',
      arrivalTime: '10:27',
      arrivalTimeMinutes: 627,
      departureTime: '10:29',
      departureTimeMinutes: 629,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 310052.82
    },
    {
      stopName: 'Albury Railway Station',
      stopNumber: null,
      suburb: 'Albury (NSW)',
      stopGTFSID: 'nsw:rail:ABY',
      arrivalTime: '10:43',
      arrivalTimeMinutes: 643,
      departureTime: '10:43',
      departureTimeMinutes: 643,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 316035.38
    }
  ],
  origin: 'Southern Cross Railway Station',
  departureTime: '07:07',
  destination: 'Albury Railway Station',
  destinationArrivalTime: '10:43'
}, {
  mode: 'regional train',
  routeName: 'Albury',
  routeNumber: null,
  routeGTFSID: '1-ABY',
  operationDays: [ '20251208', '20251209' ],
  calendarID: 'T0_2',
  tripID: '01-ABY--6-T0-8605',
  shapeID: '1-ABY-mjp-6.1.H',
  block: null,
  gtfsDirection: 0,
  runID: '8605',
  isRailReplacementBus: false,
  direction: 'Down',
  stopTimings: [
    {
      stopName: 'Southern Cross Railway Station',
      stopNumber: null,
      suburb: 'Docklands',
      stopGTFSID: 'vic:rail:SSS',
      arrivalTime: '07:07',
      arrivalTimeMinutes: 427,
      departureTime: '07:07',
      departureTimeMinutes: 427,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0
    },
    {
      stopName: 'Broadmeadows Railway Station',
      stopNumber: null,
      suburb: 'Broadmeadows',
      stopGTFSID: 'vic:rail:BMS',
      arrivalTime: '07:35',
      arrivalTimeMinutes: 455,
      departureTime: '07:35',
      departureTimeMinutes: 455,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 27298.99
    },
    {
      stopName: 'Seymour Railway Station',
      stopNumber: null,
      suburb: 'Seymour',
      stopGTFSID: 'vic:rail:SER',
      arrivalTime: '08:24',
      arrivalTimeMinutes: 504,
      departureTime: '08:26',
      departureTimeMinutes: 506,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 109304.93
    },
    {
      stopName: 'Avenel Railway Station',
      stopNumber: null,
      suburb: 'Avenel',
      stopGTFSID: 'vic:rail:AVL',
      arrivalTime: '08:37',
      arrivalTimeMinutes: 517,
      departureTime: '08:37',
      departureTimeMinutes: 517,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 126589.8
    },
    {
      stopName: 'Euroa Railway Station',
      stopNumber: null,
      suburb: 'Euroa',
      stopGTFSID: 'vic:rail:EOA',
      arrivalTime: '08:56',
      arrivalTimeMinutes: 536,
      departureTime: '08:56',
      departureTimeMinutes: 536,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 161618.19
    },
    {
      stopName: 'Violet Town Railway Station',
      stopNumber: null,
      suburb: 'Violet Town',
      stopGTFSID: 'vic:rail:VTN',
      arrivalTime: '09:07',
      arrivalTimeMinutes: 547,
      departureTime: '09:07',
      departureTimeMinutes: 547,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 179810.33
    },
    {
      stopName: 'Benalla Railway Station',
      stopNumber: null,
      suburb: 'Benalla',
      stopGTFSID: 'vic:rail:BXA',
      arrivalTime: '09:22',
      arrivalTimeMinutes: 562,
      departureTime: '09:24',
      departureTimeMinutes: 564,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 205933.09
    },
    {
      stopName: 'Wangaratta Railway Station',
      stopNumber: null,
      suburb: 'Wangaratta',
      stopGTFSID: 'vic:rail:WRT',
      arrivalTime: '09:47',
      arrivalTimeMinutes: 587,
      departureTime: '09:49',
      departureTimeMinutes: 589,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 244660.43
    },
    {
      stopName: 'Springhurst Railway Station',
      stopNumber: null,
      suburb: 'Springhurst',
      stopGTFSID: 'vic:rail:SHT',
      arrivalTime: '10:02',
      arrivalTimeMinutes: 602,
      departureTime: '10:02',
      departureTimeMinutes: 602,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 268445.71
    },
    {
      stopName: 'Chiltern Railway Station',
      stopNumber: null,
      suburb: 'Chiltern',
      stopGTFSID: 'vic:rail:CHI',
      arrivalTime: '10:10',
      arrivalTimeMinutes: 610,
      departureTime: '10:10',
      departureTimeMinutes: 610,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 282195.29
    },
    {
      stopName: 'Wodonga Railway Station',
      stopNumber: null,
      suburb: 'Wodonga',
      stopGTFSID: 'vic:rail:WOD',
      arrivalTime: '10:27',
      arrivalTimeMinutes: 627,
      departureTime: '10:29',
      departureTimeMinutes: 629,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 310052.82
    },
    {
      stopName: 'Albury Railway Station',
      stopNumber: null,
      suburb: 'Albury (NSW)',
      stopGTFSID: 'nsw:rail:ABY',
      arrivalTime: '10:43',
      arrivalTimeMinutes: 643,
      departureTime: '10:43',
      departureTimeMinutes: 643,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 316035.38
    }
  ],
  origin: 'Southern Cross Railway Station',
  departureTime: '07:07',
  destination: 'Albury Railway Station',
  destinationArrivalTime: '10:43'
}]