export default {
  stopName: 'Caulfield Railway Station',
  suburb: [ 'Caulfield East' ],
  cleanSuburbs: [ 'caulfield-east' ],
  bays: [
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'station',
      parentStopGTFSID: null,
      vnetStationName: 'Caulfield'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14251',
      location: { type: 'Point', coordinates: [ 145.04208396, -37.87736201 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14252',
      location: { type: 'Point', coordinates: [ 145.04231148, -37.87735678 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14253',
      location: { type: 'Point', coordinates: [ 145.04238158, -37.87728586 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14254',
      location: { type: 'Point', coordinates: [ 145.04243037, -37.8771605 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '22248',
      location: { type: 'Point', coordinates: [ 145.04251962, -37.87722507 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Rail Replacement Bus Stop',
      fullStopName: 'Caulfield Rail Replacement Bus Stop',
      stopGTFSID: '26135',
      location: { type: 'Point', coordinates: [ 145.04199844, -37.87758588 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Bike & Ride',
      fullStopName: 'Bike & Ride',
      stopGTFSID: 'vic:rail:CFD_BR1',
      location: { type: 'Point', coordinates: [ 145.04180495, -37.87673556 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Connex',
      fullStopName: 'Connex',
      stopGTFSID: 'vic:rail:CFD_ConX',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 1',
      fullStopName: 'Decision point 1',
      stopGTFSID: 'vic:rail:CFD_DP1',
      location: { type: 'Point', coordinates: [ 145.0419336, -37.87745864 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 2',
      fullStopName: 'Decision point 2',
      stopGTFSID: 'vic:rail:CFD_DP2',
      location: { type: 'Point', coordinates: [ 145.04193273, -37.87706211 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 3',
      fullStopName: 'Decision point 3',
      stopGTFSID: 'vic:rail:CFD_DP3',
      location: { type: 'Point', coordinates: [ 145.04213069, -37.87688516 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 4',
      fullStopName: 'Decision point 4',
      stopGTFSID: 'vic:rail:CFD_DP4',
      location: { type: 'Point', coordinates: [ 145.04226841, -37.87726595 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Normanby Rd',
      fullStopName: 'Normanby Road',
      stopGTFSID: 'vic:rail:CFD_EN1',
      location: { type: 'Point', coordinates: [ 145.04175439, -37.87735653 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Normanby Rd',
      fullStopName: 'Normanby Road',
      stopGTFSID: 'vic:rail:CFD_EN2',
      location: { type: 'Point', coordinates: [ 145.04207919, -37.87754217 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Normanby Rd',
      fullStopName: 'Normanby Road',
      stopGTFSID: 'vic:rail:CFD_EN3',
      location: { type: 'Point', coordinates: [ 145.04166372, -37.87734601 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Sir John Monash Dr',
      fullStopName: 'Sir John Monash Drive',
      stopGTFSID: 'vic:rail:CFD_EN4',
      location: { type: 'Point', coordinates: [ 145.04234304, -37.87702387 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Sir John Monash Dr',
      fullStopName: 'Sir John Monash Drive',
      stopGTFSID: 'vic:rail:CFD_EN5',
      location: { type: 'Point', coordinates: [ 145.04281318, -37.87730205 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Sir John Monash Dr',
      fullStopName: 'Sir John Monash Drive',
      stopGTFSID: 'vic:rail:CFD_EN6',
      location: { type: 'Point', coordinates: [ 145.04195197, -37.87676504 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Kiss & Ride',
      fullStopName: 'Kiss & Ride',
      stopGTFSID: 'vic:rail:CFD_KR1',
      location: { type: 'Point', coordinates: [ 145.042131, -37.87773228 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Park & Ride',
      fullStopName: 'Park & Ride',
      stopGTFSID: 'vic:rail:CFD_PR1',
      location: { type: 'Point', coordinates: [ 145.04296362, -37.87806154 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Taxi Zone',
      fullStopName: 'Taxi Zone',
      stopGTFSID: 'vic:rail:CFD_TX1',
      location: { type: 'Point', coordinates: [ 145.0427597, -37.87717499 ] },
      stopNumber: null,
      mode: 'regional train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14251',
      location: { type: 'Point', coordinates: [ 145.04208396, -37.87736201 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '1'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14252',
      location: { type: 'Point', coordinates: [ 145.04231148, -37.87735678 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '2'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14253',
      location: { type: 'Point', coordinates: [ 145.04238158, -37.87728586 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '3'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '14254',
      location: { type: 'Point', coordinates: [ 145.04243037, -37.8771605 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: '4'
    },
    {
      originalName: 'Caulfield Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '22248',
      location: { type: 'Point', coordinates: [ 145.04251962, -37.87722507 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: '26135',
      location: { type: 'Point', coordinates: [ 145.04199844, -37.87758588 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD',
      platform: 'RRB'
    },
    {
      originalName: 'Caulfield Railway Station',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'station',
      parentStopGTFSID: null
    },
    {
      originalName: 'Bike & Ride',
      fullStopName: 'Bike & Ride',
      stopGTFSID: 'vic:rail:CFD_BR1',
      location: { type: 'Point', coordinates: [ 145.04180495, -37.87673556 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Connex',
      fullStopName: 'Connex',
      stopGTFSID: 'vic:rail:CFD_ConX',
      location: { type: 'Point', coordinates: [ 145.04252478, -37.87745946 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 1',
      fullStopName: 'Decision point 1',
      stopGTFSID: 'vic:rail:CFD_DP1',
      location: { type: 'Point', coordinates: [ 145.0419336, -37.87745864 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 2',
      fullStopName: 'Decision point 2',
      stopGTFSID: 'vic:rail:CFD_DP2',
      location: { type: 'Point', coordinates: [ 145.04193273, -37.87706211 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 3',
      fullStopName: 'Decision point 3',
      stopGTFSID: 'vic:rail:CFD_DP3',
      location: { type: 'Point', coordinates: [ 145.04213069, -37.87688516 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Decision point 4',
      fullStopName: 'Decision point 4',
      stopGTFSID: 'vic:rail:CFD_DP4',
      location: { type: 'Point', coordinates: [ 145.04226841, -37.87726595 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Normanby Rd',
      fullStopName: 'Normanby Road',
      stopGTFSID: 'vic:rail:CFD_EN1',
      location: { type: 'Point', coordinates: [ 145.04175439, -37.87735653 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Normanby Rd',
      fullStopName: 'Normanby Road',
      stopGTFSID: 'vic:rail:CFD_EN2',
      location: { type: 'Point', coordinates: [ 145.04207919, -37.87754217 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Normanby Rd',
      fullStopName: 'Normanby Road',
      stopGTFSID: 'vic:rail:CFD_EN3',
      location: { type: 'Point', coordinates: [ 145.04166372, -37.87734601 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Sir John Monash Dr',
      fullStopName: 'Sir John Monash Drive',
      stopGTFSID: 'vic:rail:CFD_EN4',
      location: { type: 'Point', coordinates: [ 145.04234304, -37.87702387 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Sir John Monash Dr',
      fullStopName: 'Sir John Monash Drive',
      stopGTFSID: 'vic:rail:CFD_EN5',
      location: { type: 'Point', coordinates: [ 145.04281318, -37.87730205 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Sir John Monash Dr',
      fullStopName: 'Sir John Monash Drive',
      stopGTFSID: 'vic:rail:CFD_EN6',
      location: { type: 'Point', coordinates: [ 145.04195197, -37.87676504 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'entrance',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Kiss & Ride',
      fullStopName: 'Kiss & Ride',
      stopGTFSID: 'vic:rail:CFD_KR1',
      location: { type: 'Point', coordinates: [ 145.042131, -37.87773228 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Park & Ride',
      fullStopName: 'Park & Ride',
      stopGTFSID: 'vic:rail:CFD_PR1',
      location: { type: 'Point', coordinates: [ 145.04296362, -37.87806154 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Taxi Zone',
      fullStopName: 'Taxi Zone',
      stopGTFSID: 'vic:rail:CFD_TX1',
      location: { type: 'Point', coordinates: [ 145.0427597, -37.87717499 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'generic',
      parentStopGTFSID: 'vic:rail:CFD'
    },
    {
      originalName: 'Caulfield Railway Station/Derby Rd #57',
      fullStopName: 'Caulfield Railway Station/Derby Road',
      stopGTFSID: '18457',
      location: { type: 'Point', coordinates: [ 145.04193878, -37.87640435 ] },
      stopNumber: '57',
      mode: 'tram',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null,
      levelAccess: false,
      tramTrackerID: '1089',
      tramTrackerName: 'Caulfield Railway Station & Derby Road'
    },
    {
      originalName: 'Caulfield Railway Station/Derby Rd #57',
      fullStopName: 'Caulfield Railway Station/Derby Road',
      stopGTFSID: '18651',
      location: { type: 'Point', coordinates: [ 145.0416774, -37.8764 ] },
      stopNumber: '57',
      mode: 'tram',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null,
      levelAccess: false,
      tramTrackerID: '2089',
      tramTrackerName: 'Caulfield Railway Station & Derby Road'
    },
    {
      originalName: 'Caulfield Station/Normanby Rd',
      fullStopName: 'Caulfield Railway Station/Normanby Road',
      stopGTFSID: '14907',
      location: { type: 'Point', coordinates: [ 145.04201124, -37.87753202 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '20583',
      location: { type: 'Point', coordinates: [ 145.04232245, -37.87694242 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Railway Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '22022',
      location: { type: 'Point', coordinates: [ 145.04315316, -37.87734375 ] },
      stopNumber: null,
      mode: 'bus',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield Station/Sir John Monash Dr',
      fullStopName: 'Caulfield Railway Station/Sir John Monash Drive',
      stopGTFSID: '52537',
      location: { type: 'Point', coordinates: [ 145.04232245, -37.87694242 ] },
      stopNumber: null,
      mode: 'regional coach',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield_Up',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'RAIL_donric_77982',
      location: { type: 'Point', coordinates: [ 145.042004, -37.877585 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield_Down',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'RAIL_donric_77739',
      location: { type: 'Point', coordinates: [ 145.04119, -37.876974 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield_Down',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'RAIL_kinetic_77739',
      location: { type: 'Point', coordinates: [ 145.041347, -37.877114 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    },
    {
      originalName: 'Caulfield_Up',
      fullStopName: 'Caulfield Railway Station',
      stopGTFSID: 'RAIL_kinetic_77982',
      location: { type: 'Point', coordinates: [ 145.042704, -37.877236 ] },
      stopNumber: null,
      mode: 'metro train',
      suburb: 'Caulfield East',
      stopType: 'stop',
      parentStopGTFSID: null
    }
  ],
  mergeName: 'Caulfield Railway Station',
  services: [],
  screenServices: [],
  cleanName: 'caulfield-railway-station',
  cleanNames: [
    'caulfield-railway-station',
    'caulfield-rail-replacement-bus-stop',
    'connex',
    'caulfield-railway-station-derby-road',
    'caulfield-railway-station-normanby-road',
    'caulfield-railway-station-sir-john-monash-drive'
  ],
  codedSuburbs: [ 'caulfield-east' ],
  codedName: 'caulfield-railway-station',
  codedNames: [
    'caulfield-railway-station',
    'caulfield-rail-replacement-bus-stop',
    'connex',
    'caulfield-railway-station-derby-road',
    'caulfield-railway-station-normanby-road',
    'caulfield-railway-station-sir-john-monash-drive'
  ]
}