export default [[
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Belgrave",
    "time_seconds": "13200",
    "time_str": "3:40 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "2",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Tecoma",
    "time_seconds": "13320",
    "time_str": "3:42 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Upwey",
    "time_seconds": "13440",
    "time_str": "3:44 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Upper Ferntree Gully",
    "time_seconds": "13740",
    "time_str": "3:49 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Ferntree Gully",
    "time_seconds": "13920",
    "time_str": "3:52 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Boronia",
    "time_seconds": "14040",
    "time_str": "3:54 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Bayswater",
    "time_seconds": "14220",
    "time_str": "3:57 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Heathmont",
    "time_seconds": "14460",
    "time_str": "4:01 AM",
    "is_arrival": "0",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  },
  {
    "timetable_num": "0",
    "day_type": "2",
    "to_city": "1",
    "station": "Ringwood",
    "time_seconds": "14640",
    "time_str": "4:04 AM",
    "is_arrival": "1",
    "trip_id": "3154",
    "platform": "1",
    "forms_trip_id": "3333",
    "status": "S",
    "is_opr": true,
    "date": "2025-10-05"
  }
]]