export default {
  mode: 'metro train',
  routeName: 'Stony Point',
  routeNumber: null,
  routeGTFSID: '2-STY',
  operationDays: '20250914',
  tripID: '02-STY--15-T3-8507',
  shapeID: '2-STY-vpt-15.2.H',
  block: null,
  gtfsDirection: 0,
  runID: '8507',
  isRailReplacementBus: false,
  direction: 'Down',
  stopTimings: [
    {
      stopName: 'Frankston Railway Station',
      stopNumber: null,
      suburb: 'Frankston',
      stopGTFSID: 'vic:rail:FKN',
      arrivalTime: '13:07',
      arrivalTimeMinutes: 787,
      departureTime: '13:07',
      departureTimeMinutes: 787,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: '0.00',
      platform: '3',
      scheduledDepartureTime: '2025-09-14T03:07:00.000Z',
      actualDepartureTimeMS: 1757819220000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Leawarra Railway Station',
      stopNumber: null,
      suburb: 'Frankston',
      stopGTFSID: 'vic:rail:LWA',
      arrivalTime: '13:09',
      arrivalTimeMinutes: 789,
      departureTime: '13:09',
      departureTimeMinutes: 789,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '1886.15',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:09:00.000Z',
      actualDepartureTimeMS: 1757819340000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Baxter Railway Station',
      stopNumber: null,
      suburb: 'Baxter',
      stopGTFSID: 'vic:rail:BXR',
      arrivalTime: '13:16',
      arrivalTimeMinutes: 796,
      departureTime: '13:16',
      departureTimeMinutes: 796,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '8082.16',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:16:00.000Z',
      actualDepartureTimeMS: 1757819760000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Somerville Railway Station',
      stopNumber: null,
      suburb: 'Somerville',
      stopGTFSID: 'vic:rail:SVE',
      arrivalTime: '13:20',
      arrivalTimeMinutes: 800,
      departureTime: '13:20',
      departureTimeMinutes: 800,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '11929.29',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:20:00.000Z',
      actualDepartureTimeMS: 1757820000000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Tyabb Railway Station',
      stopNumber: null,
      suburb: 'Tyabb',
      stopGTFSID: 'vic:rail:TAB',
      arrivalTime: '13:24',
      arrivalTimeMinutes: 804,
      departureTime: '13:24',
      departureTimeMinutes: 804,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '15950.29',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:24:00.000Z',
      actualDepartureTimeMS: 1757820240000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Hastings Railway Station',
      stopNumber: null,
      suburb: 'Hastings',
      stopGTFSID: 'vic:rail:HST',
      arrivalTime: '13:29',
      arrivalTimeMinutes: 809,
      departureTime: '13:29',
      departureTimeMinutes: 809,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '21128.22',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:29:00.000Z',
      actualDepartureTimeMS: 1757820540000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Bittern Railway Station',
      stopNumber: null,
      suburb: 'Bittern',
      stopGTFSID: 'vic:rail:BIT',
      arrivalTime: '13:33',
      arrivalTimeMinutes: 813,
      departureTime: '13:33',
      departureTimeMinutes: 813,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '24793.50',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:33:00.000Z',
      actualDepartureTimeMS: 1757820780000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Morradoo Railway Station',
      stopNumber: null,
      suburb: 'Crib Point',
      stopGTFSID: 'vic:rail:MRO',
      arrivalTime: '13:36',
      arrivalTimeMinutes: 816,
      departureTime: '13:36',
      departureTimeMinutes: 816,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '27091.38',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:36:00.000Z',
      actualDepartureTimeMS: 1757820960000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Crib Point Railway Station',
      stopNumber: null,
      suburb: 'Crib Point',
      stopGTFSID: 'vic:rail:CPT',
      arrivalTime: '13:39',
      arrivalTimeMinutes: 819,
      departureTime: '13:39',
      departureTimeMinutes: 819,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: '28915.51',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:39:00.000Z',
      actualDepartureTimeMS: 1757821140000,
      estimatedDepartureTime: null,
      cancelled: false
    },
    {
      stopName: 'Stony Point Railway Station',
      stopNumber: null,
      suburb: 'Crib Point',
      stopGTFSID: 'vic:rail:STY',
      arrivalTime: '13:43',
      arrivalTimeMinutes: 823,
      departureTime: '13:43',
      departureTimeMinutes: 823,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: '30725.98',
      platform: '1',
      scheduledDepartureTime: '2025-09-14T03:43:00.000Z',
      actualDepartureTimeMS: 1757821380000,
      estimatedDepartureTime: null,
      cancelled: false
    }
  ],
  origin: 'Frankston Railway Station',
  departureTime: '13:07',
  destination: 'Stony Point Railway Station',
  destinationArrivalTime: '13:43',
  trueOrigin: 'Frankston Railway Station',
  trueDestination: 'Stony Point Railway Station',
  trueDepartureTime: '13:07',
  trueDestinationArrivalTime: '13:43'
}