const plat = (p, t) =>  ({ platform: p, type: t })
const conc = (t, q) =>  ({ concourse: true, type: t, query: q })
const platr = (c, e, t) => Array(c).fill(0).map((_, p) => plat(p + 1, t)).filter(p => !e.includes(p.platform))

const sl = (t, l) => ({ stationList: true, type: t, location: l || null })
const plat_c = (p, pos) => ({ platform: p, type: 'platform', capacity: pos })

const capPIDs = [
  plat(1, 'platform'), plat_c(1, 0), plat_c(1, 9),
  plat(2, 'platform'), plat_c(2, 0), plat_c(2, 9)  
]

const psdPID = p => Array(10).fill(0).map((_, pos) => ({ type: 'psd', platform: p, capacity: pos }))
const psdPIDs = [
  ...psdPID(1), ...psdPID(2)
]

module.exports = {
  "Dingee": [],
  "Pyramid": [],
  "Rockbank": [...platr(2, [], 'vline-half-platform')],
  "Melton": [...platr(2, [], 'vline-half-platform')],
  "Ballan": [...platr(2, [], 'vline-half-platform')],
  "Ballarat": [...platr(2, [], 'vline-half-platform')],
  "Ararat": [],
  "Castlemaine": [],
  "Maryborough": [],
  "Talbot": [],
  "Bendigo": [...platr(2, [], 'vline-half-platform')],
  "Kangaroo Flat": [],
  "Malmsbury": [],
  "Kyneton": [],
  "Woodend": [],
  "Macedon": [],
  "Riddells Creek": [],
  "Clarkefield": [...platr(2, [], 'vline-half-platform')],
  "Gisborne": [],
  "Sunbury": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Diggers Rest": [...platr(2, [], 'half-platform-bold')],
  "Craigieburn": [...platr(2, [], 'half-platform-bold')],
  "Roxburgh Park": [...platr(2, [], 'half-platform-bold'), conc('up-down')],
  "Upfield": [...platr(1, [], 'half-platform-bold')],
  "Coolaroo": [...platr(2, [], 'half-platform-bold')],
  "Watergardens": [...platr(3, [], 'half-platform-bold'), conc('up-down')],
  "Keilor Plains": [...platr(2, [], 'half-platform-bold')],
  "Gowrie": [...platr(2, [], 'half-platform-bold')],
  "Broadmeadows": [...platr(2, [], 'half-platform-bold'), conc('up-down')],
  "Jacana": [],
  "Glenroy": [...platr(2, [], 'platform'), conc('up-down')],
  "Oak Park": [],
  "Fawkner": [],
  "Pascoe Vale": [],
  "Strathmore": [],
  "Glenbervie": [],
  "Essendon": [...platr(3, [], 'half-platform-bold')],
  "Brunswick": [],
  "Jewell": [],
  "Royal Park": [],
  "Moonee Ponds": [...platr(2, [], 'half-platform-bold')],
  "Ascot Vale": [...platr(2, [], 'half-platform-bold')],
  "Flemington Racecourse": [],
  "Newmarket": [...platr(2, [], 'half-platform-bold')],
  "Kensington": [...platr(2, [], 'half-platform-bold')],
  "South Kensington": [],
  "Flemington Bridge": [],
  "Macaulay": [],
  "North Melbourne": [...platr(6, [], 'platform'), ...platr(6, [], 'pre-platform-vertical'), sl('line-group-portrait')],
  "Flagstaff": [...platr(4, [], 'platform'), conc('interchange')],
  "Southern Cross": [...platr(8, [], 'sss-platform')],
  "Footscray": [...platr(2, [], 'half-platform'), plat(3, 'vline-half-platform'), plat(4, 'vline-half-platform'), plat(5, 'half-platform'), plat(6, 'half-platform'), conc('up-down'), conc('interchange')],
  "Tottenham": [...platr(2, [], 'half-platform-bold')],
  "Middle Footscray": [],
  "West Footscray": [plat(1, 'platform'), plat(2, 'half-platform-bold'), conc('up-down')],
  "Seddon": [...platr(2, [], 'half-platform')],
  "Yarraville": [...platr(2, [], 'half-platform')],
  "St. Albans": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Ginifer": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Albion": [...platr(2, [], 'half-platform-bold')],
  "Sunshine": [...platr(2, [], 'half-platform'), plat(3, 'vline-half-platform'), plat(4, 'vline-half-platform'), conc('up-down')], // 3, 4 vline style
  "Shepparton": [],
  "Murchison East": [],
  "Wodonga": [],
  "Bairnsdale": [],
  "Seymour": [],
  "Wandong": [],
  "Heathcote Junction": [],
  "Lilydale": [...platr(2, [], 'platform'), conc('up-down')],
  "South Morang": [...platr(2, [], 'half-platform-bold')],
  "Epping": [...platr(2, [], 'half-platform-bold')],
  "Darebin": [], // Nothing
  "Box Hill": [...platr(4, [1], 'platform'), conc('up-down')],
  "Union": [...platr(3, [], 'platform')],
  "Chatham": [...platr(2, [], 'half-platform-bold')],
  "Canterbury": [...platr(2, [], 'half-platform'), plat(3, 'pre-platform-vertical')],
  "Auburn": [...platr(3, [], 'half-platform-bold')],
  "Moreland": [...platr(2, [], 'platform'), conc('up-down')],
  "Northcote": [plat(1, 'half-platform-bold'), plat(2, '2-line-led')],
  "Merri": [],
  "Anstey": [],
  "Bell": [],
  "Thornbury": [],
  "Alphington": [...platr(2, [], 'half-platform-bold')], // Both platforms
  "Croxton": [],
  "Fairfield": [...platr(2, [], 'half-platform-bold')], // Both platforms
  "Dennis": [...platr(2, [], 'half-platform')], // Plat 1 only
  "Westgarth": [...platr(2, [], 'half-platform')], // Plat 1 only
  "Rushall": [],
  "Clifton Hill": [...platr(2, [], 'half-platform-bold')],
  "Victoria Park": [...platr(2, [], 'half-platform-bold')],
  "Glenferrie": [...platr(3, [], 'half-platform-bold')],
  "Hawthorn": [...platr(3, [], 'half-platform-bold')],
  "Collingwood": [...platr(2, [], 'half-platform-bold')],
  "North Richmond": [...platr(2, [], 'half-platform-bold')],
  "West Richmond": [...platr(2, [], 'half-platform-bold')],
  "Flinders Street": [
    ...platr(14, [11], 'fss-platform'),
    plat(1, 'pre-plat-landscape'),
    ...platr(9, [1], 'fss-escalator'),
    plat(10, 'pre-plat-landscape'),
    plat(12, 'pre-plat-landscape'),
    plat(13, 'pre-plat-landscape'),
    plat(14, 'pre-plat-landscape'),
    plat(null, 'trains-from-fss'),
    sl('concourse-left'),
    sl('concourse-right'),
    sl('line-group-portrait-chl'),
    sl('line-group-portrait-bly'),
    sl('line-group-portrait-nor'),
    sl('line-group-portrait-dng'),
    sl('line-group-portrait-ccy'),
  ],
  "Parliament": [...platr(4, [], 'platform'), conc('interchange')],
  "Jolimont": [...platr(2, [], 'half-platform-bold')],
  "Richmond": [...platr(10, [], 'platform'), sl('concourse-left'), sl('concourse-right'), sl('line-group-portrait')],
  "Melbourne Central": [...platr(4, [], 'platform'), sl('line-group-portrait')],
  "South Yarra": [...platr(6, [], 'platform'), conc('up-down', 'd=up'), conc('up-down', 'd=down')],
  "Prahran": [...platr(2, [], 'half-platform')],
  "Burnley": [...platr(4, [], 'half-platform-bold')],
  "East Richmond": [plat(1, 'half-platform-bold'), plat(2, '2-line-led')],
  "Heyington": [],
  "Kooyong": [...platr(2, [], 'half-platform')],
  "Tooronga": [...platr(2, [], 'half-platform-bold')],
  "Toorak": [...platr(4, [], 'half-platform'), conc('up-down')],
  "Hawksburn": [...platr(4, [], 'half-platform'), conc('up-down')],
  "Lalor": [...platr(2, [], 'half-platform-bold')],
  "Hurstbridge": [plat(1, 'half-platform-bold')],
  "Wattle Glen": [],
  "Diamond Creek": [],
  "Eltham": [...platr(2, [], 'half-platform-bold')],
  "Mooroolbark": [...platr(2, [], 'platform'), conc('up-down')],
  "Croydon": [...platr(2, [], 'platform'), conc('up-down')],
  "Ringwood": [...platr(3, [], 'half-platform-bold'), conc('up-down')],
  "Ringwood East": [...platr(2, [], 'platform'), conc('up-down')],
  "Heatherdale": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Mitcham": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Nunawading": [...platr(2, [], 'half-platform-bold')],
  "Blackburn": [...platr(3, [], 'half-platform-bold')],
  "Laburnum": [...platr(2, [], 'half-platform-bold')],
  "Thomastown": [...platr(2, [], 'half-platform-bold')],
  "Keon Park": [...platr(2, [], 'platform')],
  "Ruthven": [],
  "Reservoir": [...platr(2, [], 'half-platform-bold'), conc('up-down')],
  "Regent": [],
  "Preston": [...platr(2, [], 'platform'), conc('up-down')],
  "Merlynston": [],
  "Batman": [],
  "Coburg": [...platr(2, [], 'platform'), conc('up-down')],
  "Greensborough": [...platr(2, [], 'half-platform-bold')],
  "Montmorency": [],
  "Watsonia": [...platr(2, [], 'half-platform-bold')],
  "Macleod": [...platr(3, [], 'half-platform-bold')], // Platform 1 only - 2 is LED and 3 has nothing
  "Heidelberg": [...platr(2, [], 'half-platform-bold')],
  "Ivanhoe": [...platr(2, [], 'half-platform-bold')],
  "Eaglemont": [], // Nothing
  "Windsor": [...platr(2, [], 'half-platform')],
  "Balaclava": [...platr(2, [], 'half-platform')],
  "Armadale": [...platr(4, [], 'half-platform'), conc('up-down')],
  "Malvern": [...platr(4, [], 'half-platform'), conc('up-down')],
  "Caulfield": [...platr(4, [], 'platform'), conc('up-down')],
  "Glen Huntly": [ ...platr(3, [], 'platform'), conc('up-down')],
  "Ripponlea": [...platr(2, [], 'half-platform')],
  "Elsternwick": [...platr(2, [], 'half-platform')],
  "Camberwell": [...platr(3, [], 'half-platform-bold')],
  "East Camberwell": [...platr(3, [], 'half-platform-bold')],
  "Riversdale": [...platr(2, [], 'half-platform-bold')],
  "Willison": [],
  "Burwood": [],
  "Hartwell": [],
  "Gardiner": [...platr(2, [], 'platform'), conc('up-down')],
  "Jordanville": [...platr(2, [], 'half-platform-bold')],
  "Mount Waverley": [...platr(2, [], 'half-platform-bold')],
  "Holmesglen": [],
  "Glen Iris": [...platr(2, [], 'half-platform-bold')],
  "Darling": [...platr(2, [], 'half-platform-bold')],
  "Ashburton": [],
  "Alamein": [],
  "East Malvern": [],
  "Murrumbeena": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Carnegie": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Yarraman": [...platr(2, [], 'half-platform-bold')],
  "Dandenong": [...platr(3, [], 'half-platform'), conc('up-down')],
  "Narre Warren": [...platr(2, [], 'platform'), conc('up-down')],
  "Hallam": [...platr(2, [], 'platform'), conc('up-down')],
  "Lynbrook": [...platr(2, [], 'half-platform-bold')],
  "Merinda Park": [plat(2, 'platform')],
  "Cranbourne": [...platr(2, [], 'half-platform-bold')],
  "Carrum": [...platr(2, [], 'platform'), conc('up-down')],
  "Seaford": [...platr(2, [], 'half-platform')],
  "Kananook": [...platr(2, [], 'half-platform')],
  "Mentone": [...platr(2, [], 'platform'), conc('up-down')],
  "Parkdale": [...platr(2, [], 'half-platform')],
  "Mordialloc": [...platr(2, [], 'half-platform')],
  "Aspendale": [],
  "Edithvale": [...platr(2, [], 'platform'), conc('up-down')],
  "Chelsea": [...platr(2, [], 'platform'), conc('up-down')],
  "Bonbeach": [...platr(2, [], 'platform'), conc('up-down')],
  "Tecoma": [],
  "Belgrave": [...platr(2, [], 'half-platform-bold')],
  "Tynong": [],
  "Garfield": [...platr(2, [], 'vline-half-platform')],
  "Nar Nar Goon": [...platr(2, [], 'vline-half-platform')],
  "Beaconsfield": [],
  "Berwick": [...platr(2, [], 'half-platform-bold')],
  "Cardinia Road": [...platr(2, [], 'half-platform-bold')],
  "Pakenham": [...platr(2, [], 'platform'), conc('up-down')],
  "East Pakenham": [...platr(2, [], 'platform'), conc('up-down')],
  "Officer": [],
  "Frankston": [... platr(3, [], 'platform'), conc('up-down')],
  "Leawarra": [],
  "Baxter": [],
  "Somerville": [],
  "Tyabb": [],
  "Hastings": [],
  "Bittern": [],
  "Stony Point": [],
  "Morradoo": [],
  "Crib Point": [],
  "Drouin": [],
  "Longwarry": [...platr(1, [], 'vline-half-platform')],
  "Bunyip": [],
  "Trafalgar": [],
  "Moe": [],
  "Warragul": [],
  "Yarragon": [platr(2, 'vline-half-platform')],
  "Stratford": [],
  "Sale": [],
  "Traralgon": [plat(1, 'vline-half-platform')],
  "Rosedale": [],
  "Spotswood": [],
  "Newport": [...platr(2, [], 'half-platform')],
  "Williamstown": [...platr(1, [], 'half-platform')],
  "North Williamstown": [...platr(2, [], 'half-platform')],
  "Williamstown Beach": [],
  "North Geelong": [],
  "Geelong": [...platr(3, [], 'vline-half-platform')],
  "South Geelong": [],
  "Warrnambool": [],
  "Ormond": [...platr(3, [], 'half-platform'), conc('up-down')],
  "Oakleigh": [...platr(2, [], 'half-platform-bold'), ...platr(2, [], 'platform'), conc('up-down')],
  "McKinnon": [...platr(3, [], 'half-platform'), conc('up-down')],
  "Bentleigh": [...platr(3, [], 'half-platform'), conc('up-down')],
  "Patterson": [...platr(3, [], 'half-platform')],
  "Huntingdale": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Clayton": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Westall": [...platr(3, [], 'half-platform-bold'), conc('up-down')],
  "Moorabbin": [...platr(3, [], 'half-platform')],
  "Highett": [...platr(2, [], 'half-platform')],
  "Southland": [...platr(2, [], 'half-platform')],
  "Cheltenham": [...platr(3, [], 'platform'), conc('up-down')],
  "Brighton Beach": [...platr(2, [], 'half-platform')],
  "Gardenvale": [...platr(2, [], 'half-platform')],
  "North Brighton": [...platr(2, [], 'half-platform')],
  "Middle Brighton": [...platr(2, [], 'half-platform')],
  "Hampton": [...platr(2, [], 'half-platform-bold')],
  "Sandringham": [...platr(1, [], 'half-platform')],
  "Glen Waverley": [...platr(2, [], 'half-platform-bold'), conc('up-down')],
  "Syndal": [...platr(2, [], 'half-platform-bold')],
  "Heathmont": [...platr(2, [], 'half-platform-bold')],
  "Bayswater": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Boronia": [...platr(2, [], 'half-platform-bold')],
  "Ferntree Gully": [...platr(2, [], 'half-platform-bold')],
  "Upper Ferntree Gully": [...platr(2, [], 'half-platform-bold')],
  "Upwey": [],
  "Springvale": [...platr(2, [], 'half-platform-bold')],
  "Sandown Park": [...platr(2, [], 'half-platform-bold')],
  "Noble Park": [...platr(2, [], 'half-platform')],
  "Little River": [...platr(2, [], 'vline-half-platform')],
  "Lara": [...platr(2, [], 'vline-half-platform')],
  "Corio": [],
  "North Shore": [],
  "Aircraft": [],
  "Williams Landing": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Hoppers Crossing": [...platr(2, [], 'half-platform')],
  "Werribee": [...platr(3, [], 'half-platform'), conc('up-down')],
  "Westona": [...platr(2, [], 'half-platform')],
  "Seaholme": [...platr(1, [], 'half-platform')],
  "Altona": [...platr(1, [], 'half-platform')],
  "Laverton": [...platr(3, [], 'half-platform'), conc('up-down')],
  "Ardeer": [...platr(2, [], 'vline-half-platform')],
  "Deer Park": [...platr(2, [], 'vline-half-platform')],
  "Tarneit": [...platr(2, [], 'vline-half-platform')],
  "Wyndham Vale": [...platr(2, [], 'vline-half-platform')],
  "Bacchus Marsh": [...platr(2, [], 'vline-half-platform')],
  "Cobblebank": [...platr(2, [], 'vline-half-platform')],
  "Caroline Springs": [...platr(2, [], 'vline-half-platform')],
  "Donnybrook": [...platr(2, [], 'vline-half-platform')],
  "Wallan": [],
  "Kilmore East": [],
  "Broadford": [],
  "Tallarook": [],
  "Avenel": [],
  "Euroa": [],
  "Violet Town": [],
  "Springhurst": [],
  "Chiltern": [],
  "Benalla": [],
  "Albury": [],
  "Hughesdale": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Rosanna": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Middle Gorge": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Hawkstowe": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Mernda": [...platr(2, [], 'half-platform'), conc('up-down')],
  "Wendouree": [],
  "Marshall": [],
  "Waurn Ponds": [],
  "Winchelsea": [],
  "Birregurra": [],
  "Colac": [...platr(1, [], 'vline-half-platform')],
  "Camperdown": [],
  "Terang": [],
  "Sherwood Park": [],
  "Warnambool": [],
  "Beaufort": [],
  "Creswick": [],
  "Clunes": [],
  "Eaglehawk": [],
  "Kerang": [],
  "Swan Hill": [],
  "Epsom": [],
  "Elmore": [],
  "Rochester": [],
  "Echuca": [],
  "Nagambie": [],
  "Mooroopna": [],
  "Wangaratta": [],
  "Morwell": [],

  "Anzac": [...capPIDs, ...psdPIDs, sl('concourse-trains')],
  "Town Hall": [...capPIDs, ...psdPIDs, sl('concourse-trains')],
  "State Library": [...capPIDs, ...psdPIDs, sl('concourse-trains')],
  "Parkville": [...capPIDs, ...psdPIDs, sl('concourse-trains')],
  "Arden": [...capPIDs, ...psdPIDs, sl('concourse-trains')]
}