export default {
  mode: 'metro train',
  routeGTFSID: '2-BEG',
  operationDays: '20251004',
  tripID: '02-BEG--18-T2-3152',
  shapeID: '2-BEG-vpt-18.15.R',
  block: null,
  gtfsDirection: null,
  runID: '3152',
  isRailReplacementBus: false,
  vehicle: null,
  direction: 'Up',
  routeName: 'Belgrave',
  routeNumber: null,
  origin: 'Belgrave Railway Station',
  destination: 'Ringwood Railway Station',
  departureTime: '25:36',
  destinationArrivalTime: '26:04',
  stopTimings: [
    {
      stopName: 'Belgrave Railway Station',
      stopNumber: null,
      suburb: 'Belgrave',
      stopGTFSID: 'vic:rail:BEG',
      arrivalTime: '01:36',
      arrivalTimeMinutes: 1536,
      departureTime: '01:36',
      departureTimeMinutes: 1536,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:36:00.000Z',
      actualDepartureTimeMS: 1759592160000,
      platform: '2',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0
    },
    {
      stopName: 'Tecoma Railway Station',
      stopNumber: null,
      suburb: 'Tecoma',
      stopGTFSID: 'vic:rail:TCM',
      arrivalTime: '01:38',
      arrivalTimeMinutes: 1538,
      departureTime: '01:38',
      departureTimeMinutes: 1538,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:38:00.000Z',
      actualDepartureTimeMS: 1759592280000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 1193.84
    },
    {
      stopName: 'Upwey Railway Station',
      stopNumber: null,
      suburb: 'Upwey',
      stopGTFSID: 'vic:rail:UPW',
      arrivalTime: '01:40',
      arrivalTimeMinutes: 1540,
      departureTime: '01:40',
      departureTimeMinutes: 1540,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:40:00.000Z',
      actualDepartureTimeMS: 1759592400000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 2338.82
    },
    {
      stopName: 'Upper Ferntree Gully Railway Station',
      stopNumber: null,
      suburb: 'Upper Ferntree Gully',
      stopGTFSID: 'vic:rail:UFG',
      arrivalTime: '01:49',
      arrivalTimeMinutes: 1549,
      departureTime: '01:49',
      departureTimeMinutes: 1549,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:49:00.000Z',
      actualDepartureTimeMS: 1759592940000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 4882.03
    },
    {
      stopName: 'Ferntree Gully Railway Station',
      stopNumber: null,
      suburb: 'Ferntree Gully',
      stopGTFSID: 'vic:rail:FTG',
      arrivalTime: '01:52',
      arrivalTimeMinutes: 1552,
      departureTime: '01:52',
      departureTimeMinutes: 1552,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:52:00.000Z',
      actualDepartureTimeMS: 1759593120000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 6638.64
    },
    {
      stopName: 'Boronia Railway Station',
      stopNumber: null,
      suburb: 'Boronia',
      stopGTFSID: 'vic:rail:BOR',
      arrivalTime: '01:54',
      arrivalTimeMinutes: 1554,
      departureTime: '01:54',
      departureTimeMinutes: 1554,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:54:00.000Z',
      actualDepartureTimeMS: 1759593240000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 9135.88
    },
    {
      stopName: 'Bayswater Railway Station',
      stopNumber: null,
      suburb: 'Bayswater',
      stopGTFSID: 'vic:rail:BAY',
      arrivalTime: '01:57',
      arrivalTimeMinutes: 1557,
      departureTime: '01:57',
      departureTimeMinutes: 1557,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T15:57:00.000Z',
      actualDepartureTimeMS: 1759593420000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 11681.05
    },
    {
      stopName: 'Heathmont Railway Station',
      stopNumber: null,
      suburb: 'Heathmont',
      stopGTFSID: 'vic:rail:HMT',
      arrivalTime: '03:01',
      arrivalTimeMinutes: 1561,
      departureTime: '03:01',
      departureTimeMinutes: 1561,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T16:01:00.000Z',
      actualDepartureTimeMS: 1759593660000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 14379.7
    },
    {
      stopName: 'Ringwood Railway Station',
      stopNumber: null,
      suburb: 'Ringwood',
      stopGTFSID: 'vic:rail:RWD',
      arrivalTime: '03:04',
      arrivalTimeMinutes: 1564,
      departureTime: '03:04',
      departureTimeMinutes: 1564,
      estimatedDepartureTime: null,
      scheduledDepartureTime: '2025-10-04T16:04:00.000Z',
      actualDepartureTimeMS: 1759593840000,
      platform: '1',
      cancelled: false,
      additional: false,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 16766.6
    }
  ],
  formedBy: '3675',
  forming: null,
  changes: [],
  cancelled: false,
  additional: false,
  lastUpdated: 1759574744752
}