export default {
  mode: 'regional train',
  routeName: 'Bairnsdale',
  routeGTFSID: '1-BDE',
  runID: '8469',
  operationDays: [ 'Sun' ],
  vehicle: '2x 3VL',
  isConditional: false,
  formedBy: '9632',
  forming: '7469',
  operator: 'V/Line',
  stopTimings: [
    {
      stopName: 'Southern Cross Railway Station',
      stopGTFSID: 'vic:rail:SSS',
      suburb: 'Docklands',
      arrivalTime: '18:23',
      arrivalTimeMinutes: 1103,
      departureTime: '18:23',
      departureTimeMinutes: 1103,
      platform: '15A',
      track: 'TS',
      express: false
    },
    {
      stopName: 'Flinders Street Railway Station',
      stopGTFSID: 'vic:rail:FSS',
      suburb: 'Melbourne',
      arrivalTime: '18:27',
      arrivalTimeMinutes: 1107,
      departureTime: '18:28u',
      departureTimeMinutes: 1108,
      platform: '7',
      track: 'CL',
      express: false
    },
    {
      stopName: 'Richmond Railway Station',
      stopGTFSID: 'vic:rail:RMD',
      suburb: 'Richmond',
      arrivalTime: '18:32u',
      arrivalTimeMinutes: 1112,
      departureTime: '18:32u',
      departureTimeMinutes: 1112,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Caulfield Railway Station',
      stopGTFSID: 'vic:rail:CFD',
      suburb: 'Caulfield East',
      arrivalTime: '18:41u',
      arrivalTimeMinutes: 1121,
      departureTime: '18:41u',
      departureTimeMinutes: 1121,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Oakleigh Railway Station',
      stopGTFSID: 'vic:rail:OAK',
      suburb: 'Oakleigh',
      arrivalTime: '18:48',
      arrivalTimeMinutes: 1128,
      departureTime: '18:48',
      departureTimeMinutes: 1128,
      platform: null,
      track: null,
      express: true
    },
    {
      stopName: 'Clayton Railway Station',
      stopGTFSID: 'vic:rail:CLA',
      suburb: 'Clayton',
      arrivalTime: '18:53u',
      arrivalTimeMinutes: 1133,
      departureTime: '18:53u',
      departureTimeMinutes: 1133,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Westall Railway Station',
      stopGTFSID: 'vic:rail:WTL',
      suburb: 'Clayton South',
      arrivalTime: '18:56',
      arrivalTimeMinutes: 1136,
      departureTime: '18:56',
      departureTimeMinutes: 1136,
      platform: null,
      track: null,
      express: true
    },
    {
      stopName: 'Springvale Railway Station',
      stopGTFSID: 'vic:rail:SPG',
      suburb: 'Springvale',
      arrivalTime: '18:58',
      arrivalTimeMinutes: 1138,
      departureTime: '18:58',
      departureTimeMinutes: 1138,
      platform: null,
      track: null,
      express: true
    },
    {
      stopName: 'Dandenong Railway Station',
      stopGTFSID: 'vic:rail:DNG',
      suburb: 'Dandenong',
      arrivalTime: '19:09u',
      arrivalTimeMinutes: 1149,
      departureTime: '19:09u',
      departureTimeMinutes: 1149,
      platform: '3',
      track: null,
      express: false
    },
    {
      stopName: 'Berwick Railway Station',
      stopGTFSID: 'vic:rail:BEW',
      suburb: 'Berwick',
      arrivalTime: '19:18',
      arrivalTimeMinutes: 1158,
      departureTime: '19:18',
      departureTimeMinutes: 1158,
      platform: null,
      track: null,
      express: true
    },
    {
      stopName: 'Pakenham Railway Station',
      stopGTFSID: 'vic:rail:PKM',
      suburb: 'Pakenham',
      arrivalTime: '19:29',
      arrivalTimeMinutes: 1169,
      departureTime: '19:29',
      departureTimeMinutes: 1169,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'East Pakenham Railway Station',
      stopGTFSID: 'vic:rail:EPH',
      suburb: 'Pakenham',
      arrivalTime: '19:30',
      arrivalTimeMinutes: 1170,
      departureTime: '19:30',
      departureTimeMinutes: 1170,
      platform: 'D',
      track: 'N',
      express: true
    },
    {
      stopName: 'Nar Nar Goon Railway Station',
      stopGTFSID: 'vic:rail:NNG',
      suburb: 'Nar Nar Goon',
      arrivalTime: '19:34',
      arrivalTimeMinutes: 1174,
      departureTime: '19:34',
      departureTimeMinutes: 1174,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Tynong Railway Station',
      stopGTFSID: 'vic:rail:TYN',
      suburb: 'Tynong',
      arrivalTime: '19:39',
      arrivalTimeMinutes: 1179,
      departureTime: '19:39',
      departureTimeMinutes: 1179,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Garfield Railway Station',
      stopGTFSID: 'vic:rail:GAR-V',
      suburb: 'Garfield',
      arrivalTime: '19:43',
      arrivalTimeMinutes: 1183,
      departureTime: '19:43',
      departureTimeMinutes: 1183,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Bunyip Railway Station',
      stopGTFSID: 'vic:rail:BYP',
      suburb: 'Bunyip',
      arrivalTime: '19:46',
      arrivalTimeMinutes: 1186,
      departureTime: '19:46',
      departureTimeMinutes: 1186,
      platform: '2',
      track: null,
      express: false
    },
    {
      stopName: 'Longwarry Railway Station',
      stopGTFSID: 'vic:rail:LWY',
      suburb: 'Longwarry',
      arrivalTime: '19:50',
      arrivalTimeMinutes: 1190,
      departureTime: '19:50',
      departureTimeMinutes: 1190,
      platform: '1',
      track: 'S',
      express: false
    },
    {
      stopName: 'Drouin Railway Station',
      stopGTFSID: 'vic:rail:DRN',
      suburb: 'Drouin',
      arrivalTime: '19:57',
      arrivalTimeMinutes: 1197,
      departureTime: '19:57',
      departureTimeMinutes: 1197,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Warragul Railway Station',
      stopGTFSID: 'vic:rail:WGL',
      suburb: 'Warragul',
      arrivalTime: '20:03',
      arrivalTimeMinutes: 1203,
      departureTime: '20:03',
      departureTimeMinutes: 1203,
      platform: '1',
      track: 'S',
      express: false
    },
    {
      stopName: 'Yarragon Railway Station',
      stopGTFSID: 'vic:rail:YON',
      suburb: 'Yarragon',
      arrivalTime: '20:10',
      arrivalTimeMinutes: 1210,
      departureTime: '20:10',
      departureTimeMinutes: 1210,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Trafalgar Railway Station',
      stopGTFSID: 'vic:rail:TAR',
      suburb: 'Trafalgar',
      arrivalTime: '20:16',
      arrivalTimeMinutes: 1216,
      departureTime: '20:16',
      departureTimeMinutes: 1216,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Moe Railway Station',
      stopGTFSID: 'vic:rail:MOE',
      suburb: 'Moe',
      arrivalTime: '20:22',
      arrivalTimeMinutes: 1222,
      departureTime: '20:22',
      departureTimeMinutes: 1222,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Morwell Railway Station',
      stopGTFSID: 'vic:rail:MWL',
      suburb: 'Morwell',
      arrivalTime: '20:35',
      arrivalTimeMinutes: 1235,
      departureTime: '20:35',
      departureTimeMinutes: 1235,
      platform: '2',
      track: null,
      express: false
    },
    {
      stopName: 'Traralgon Railway Station',
      stopGTFSID: 'vic:rail:TRN',
      suburb: 'Traralgon',
      arrivalTime: '20:47',
      arrivalTimeMinutes: 1247,
      departureTime: '20:50',
      departureTimeMinutes: 1247,
      platform: '1',
      track: null,
      express: false
    },
    {
      stopName: 'Rosedale Railway Station',
      stopGTFSID: 'vic:rail:ROE',
      suburb: 'Rosedale',
      arrivalTime: '21:06',
      arrivalTimeMinutes: 1266,
      departureTime: '21:06',
      departureTimeMinutes: 1266,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Sale Railway Station',
      stopGTFSID: 'vic:rail:SAE',
      suburb: 'Sale',
      arrivalTime: '21:25',
      arrivalTimeMinutes: 1285,
      departureTime: '21:25',
      departureTimeMinutes: 1285,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Stratford Railway Station',
      stopGTFSID: 'vic:rail:STD',
      suburb: 'Stratford',
      arrivalTime: '21:39',
      arrivalTimeMinutes: 1299,
      departureTime: '21:39',
      departureTimeMinutes: 1299,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Bairnsdale Railway Station',
      stopGTFSID: 'vic:rail:BDE',
      suburb: 'Bairnsdale',
      arrivalTime: '22:19',
      arrivalTimeMinutes: 1339,
      departureTime: '22:19',
      departureTimeMinutes: 1339,
      platform: null,
      track: null,
      express: false
    }
  ],
  direction: 'Down',
  origin: 'Southern Cross Railway Station',
  departureTime: '18:23',
  destination: 'Bairnsdale Railway Station',
  destinationArrivalTime: '22:19'
}