export default {
  mode: 'regional train',
  routeName: 'Geelong',
  routeNumber: null,
  routeGTFSID: '1-GEL',
  operationDays: [ '20251228' ],
  calendarID: 'T3',
  tripID: '01-GEL--4-T3-8776',
  shapeID: '1-GEL-mjp-4.11.R',
  block: null,
  gtfsDirection: 1,
  runID: '8776',
  isRailReplacementBus: false,
  direction: 'Up',
  stopTimings: [
    {
      stopName: 'Waurn Ponds Railway Station',
      stopNumber: null,
      suburb: 'Mount Duneed',
      stopGTFSID: 'vic:rail:WPP',
      arrivalTime: '14:21',
      arrivalTimeMinutes: 861,
      departureTime: '14:21',
      departureTimeMinutes: 861,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0
    },
    {
      stopName: 'Marshall Railway Station',
      stopNumber: null,
      suburb: 'Marshall',
      stopGTFSID: 'vic:rail:MAS',
      arrivalTime: '14:25',
      arrivalTimeMinutes: 865,
      departureTime: '14:25',
      departureTimeMinutes: 865,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 5075.72
    },
    {
      stopName: 'South Geelong Railway Station',
      stopNumber: null,
      suburb: 'South Geelong',
      stopGTFSID: 'vic:rail:SOG',
      arrivalTime: '14:30',
      arrivalTimeMinutes: 870,
      departureTime: '14:30',
      departureTimeMinutes: 870,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 10282.65
    },
    {
      stopName: 'Geelong Railway Station',
      stopNumber: null,
      suburb: 'Geelong',
      stopGTFSID: 'vic:rail:GEL',
      arrivalTime: '14:33',
      arrivalTimeMinutes: 873,
      departureTime: '14:35',
      departureTimeMinutes: 875,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 12121.2
    },
    {
      stopName: 'North Geelong Railway Station',
      stopNumber: null,
      suburb: 'North Geelong',
      stopGTFSID: 'vic:rail:NGL',
      arrivalTime: '14:38',
      arrivalTimeMinutes: 878,
      departureTime: '14:38',
      departureTimeMinutes: 878,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 14592.69
    },
    {
      stopName: 'North Shore Railway Station',
      stopNumber: null,
      suburb: 'North Shore',
      stopGTFSID: 'vic:rail:NSH',
      arrivalTime: '14:42',
      arrivalTimeMinutes: 882,
      departureTime: '14:42',
      departureTimeMinutes: 882,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 17633.13
    },
    {
      stopName: 'Corio Railway Station',
      stopNumber: null,
      suburb: 'Corio',
      stopGTFSID: 'vic:rail:COR',
      arrivalTime: '14:45',
      arrivalTimeMinutes: 885,
      departureTime: '14:45',
      departureTimeMinutes: 885,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 20750.68
    },
    {
      stopName: 'Lara Railway Station',
      stopNumber: null,
      suburb: 'Lara',
      stopGTFSID: 'vic:rail:LRA',
      arrivalTime: '14:49',
      arrivalTimeMinutes: 889,
      departureTime: '14:49',
      departureTimeMinutes: 889,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 27157.62
    },
    {
      stopName: 'Wyndham Vale Railway Station',
      stopNumber: null,
      suburb: 'Manor Lakes',
      stopGTFSID: 'vic:rail:WVL',
      arrivalTime: '15:02',
      arrivalTimeMinutes: 902,
      departureTime: '15:02',
      departureTimeMinutes: 902,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 52659.99
    },
    {
      stopName: 'Tarneit Railway Station',
      stopNumber: null,
      suburb: 'Tarneit',
      stopGTFSID: 'vic:rail:TNT',
      arrivalTime: '15:09',
      arrivalTimeMinutes: 909,
      departureTime: '15:09',
      departureTimeMinutes: 909,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 63796.9
    },
    {
      stopName: 'Deer Park Railway Station',
      stopNumber: null,
      suburb: 'Deer Park',
      stopGTFSID: 'vic:rail:DEK',
      arrivalTime: '15:16',
      arrivalTimeMinutes: 916,
      departureTime: '15:16',
      departureTimeMinutes: 916,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 75161.65
    },
    {
      stopName: 'Sunshine Railway Station',
      stopNumber: null,
      suburb: 'Sunshine',
      stopGTFSID: 'vic:rail:SUN',
      arrivalTime: '15:24',
      arrivalTimeMinutes: 924,
      departureTime: '15:24',
      departureTimeMinutes: 924,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 80823.23
    },
    {
      stopName: 'Footscray Railway Station',
      stopNumber: null,
      suburb: 'Footscray',
      stopGTFSID: 'vic:rail:FSY',
      arrivalTime: '15:30',
      arrivalTimeMinutes: 930,
      departureTime: '15:30',
      departureTimeMinutes: 930,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 87444.19
    },
    {
      stopName: 'Southern Cross Railway Station',
      stopNumber: null,
      suburb: 'Docklands',
      stopGTFSID: 'vic:rail:SSS',
      arrivalTime: '15:40',
      arrivalTimeMinutes: 940,
      departureTime: '15:40',
      departureTimeMinutes: 940,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 92872.52
    }
  ],
  origin: 'Waurn Ponds Railway Station',
  departureTime: '14:21',
  destination: 'Southern Cross Railway Station',
  destinationArrivalTime: '15:40'
}