export default {
  mode: 'regional train',
  routeName: 'Ballarat',
  routeGTFSID: '1-BAT',
  runID: '8141',
  operationDays: [ 'Sun' ],
  vehicle: '2x 3VL',
  isConditional: false,
  formedBy: '8140',
  forming: '8152',
  operator: 'V/Line',
  stopTimings: [
    {
      stopName: 'Southern Cross Railway Station',
      stopGTFSID: 'vic:rail:SSS',
      suburb: 'Docklands',
      arrivalTime: '17:15',
      arrivalTimeMinutes: 1035,
      departureTime: '17:15',
      departureTimeMinutes: 1035,
      platform: '3',
      track: 'MC',
      express: false
    },
    {
      stopName: 'Footscray Railway Station',
      stopGTFSID: 'vic:rail:FSY',
      suburb: 'Footscray',
      arrivalTime: '17:23u',
      arrivalTimeMinutes: 1043,
      departureTime: '17:23u',
      departureTimeMinutes: 1043,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Sunshine Railway Station',
      stopGTFSID: 'vic:rail:SUN',
      suburb: 'Sunshine',
      arrivalTime: '17:28u',
      arrivalTimeMinutes: 1048,
      departureTime: '17:28u',
      departureTimeMinutes: 1048,
      platform: '4',
      track: null,
      express: false
    },
    {
      stopName: 'Ardeer Railway Station',
      stopGTFSID: 'vic:rail:ARR',
      suburb: 'Sunshine West',
      arrivalTime: '17:32',
      arrivalTimeMinutes: 1052,
      departureTime: '17:32',
      departureTimeMinutes: 1052,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Deer Park Railway Station',
      stopGTFSID: 'vic:rail:DEK',
      suburb: 'Deer Park',
      arrivalTime: '17:35',
      arrivalTimeMinutes: 1055,
      departureTime: '17:35',
      departureTimeMinutes: 1055,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Caroline Springs Railway Station',
      stopGTFSID: 'vic:rail:RVH',
      suburb: 'Ravenhall',
      arrivalTime: '17:39',
      arrivalTimeMinutes: 1059,
      departureTime: '17:39',
      departureTimeMinutes: 1059,
      platform: '2',
      track: null,
      express: false
    },
    {
      stopName: 'Rockbank Railway Station',
      stopGTFSID: 'vic:rail:RBK',
      suburb: 'Rockbank',
      arrivalTime: '17:45',
      arrivalTimeMinutes: 1065,
      departureTime: '17:45',
      departureTimeMinutes: 1065,
      platform: null,
      track: null,
      express: false
    },
    {
      stopName: 'Cobblebank Railway Station',
      stopGTFSID: 'vic:rail:TLN',
      suburb: 'Cobblebank',
      arrivalTime: '17:49',
      arrivalTimeMinutes: 1069,
      departureTime: '17:49',
      departureTimeMinutes: 1069,
      platform: '2',
      track: null,
      express: false
    },
    {
      stopName: 'Melton Railway Station',
      stopGTFSID: 'vic:rail:MEL',
      suburb: 'Melton South',
      arrivalTime: '17:52',
      arrivalTimeMinutes: 1072,
      departureTime: '17:52',
      departureTimeMinutes: 1072,
      platform: '2',
      track: null,
      express: false
    },
    {
      stopName: 'Bacchus Marsh Railway Station',
      stopGTFSID: 'vic:rail:BAH',
      suburb: 'Maddingley',
      arrivalTime: '18:00',
      arrivalTimeMinutes: 1080,
      departureTime: '18:00',
      departureTimeMinutes: 1080,
      platform: '2',
      track: 'S',
      express: false
    },
    {
      stopName: 'Ballan Railway Station',
      stopGTFSID: 'vic:rail:BLN',
      suburb: 'Ballan',
      arrivalTime: '18:19',
      arrivalTimeMinutes: 1099,
      departureTime: '18:19',
      departureTimeMinutes: 1099,
      platform: '2',
      track: null,
      express: false
    },
    {
      stopName: 'Ballarat Railway Station',
      stopGTFSID: 'vic:rail:BAT-V',
      suburb: 'Ballarat Central',
      arrivalTime: '18:41',
      arrivalTimeMinutes: 1121,
      departureTime: '18:41',
      departureTimeMinutes: 1121,
      platform: '2',
      track: '18:44',
      express: false
    },
    {
      stopName: 'Wendouree Railway Station',
      stopGTFSID: 'vic:rail:WED',
      suburb: 'Lake Gardens',
      arrivalTime: '18:51',
      arrivalTimeMinutes: 1131,
      departureTime: '18:51',
      departureTimeMinutes: 1131,
      platform: '1',
      track: null,
      express: false
    }
  ],
  direction: 'Down',
  origin: 'Southern Cross Railway Station',
  departureTime: '17:15',
  destination: 'Wendouree Railway Station',
  destinationArrivalTime: '18:51'
} 