export default {
  mode: 'bus',
  routeName: 'The Pines SC - Nunawading Station',
  routeNumber: '273',
  routeGTFSID: '4-273',
  operationDays: [ '20251229' ],
  calendarID: 'MF11-14-273-aus',
  tripID: '14-273--1-MF11-273031',
  shapeID: '14-273-aus-1.2.R',
  block: null,
  gtfsDirection: 1,
  depotID: 14,
  runID: '14-273--MF-273031',
  stopTimings: [
    {
      stopName: 'The Pines Shopping Centre/Reynolds Road',
      stopNumber: null,
      suburb: 'Doncaster East',
      stopGTFSID: '44916',
      arrivalTime: '12:45',
      arrivalTimeMinutes: 765,
      departureTime: '12:45',
      departureTimeMinutes: 765,
      stopConditions: { pickup: 0, dropoff: 1 },
      stopDistance: 0,
      platform: 'Bay 4'
    },
    {
      stopName: 'Andersons Creek Road/Reynolds Road',
      stopNumber: null,
      suburb: 'Doncaster East',
      stopGTFSID: '4021',
      arrivalTime: '12:47',
      arrivalTimeMinutes: 767,
      departureTime: '12:47',
      departureTimeMinutes: 767,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 678.76
    },
    {
      stopName: 'Katandra Place/Reynolds Road',
      stopNumber: null,
      suburb: 'Doncaster East',
      stopGTFSID: '4104',
      arrivalTime: '12:47',
      arrivalTimeMinutes: 767,
      departureTime: '12:47',
      departureTimeMinutes: 767,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 963.23
    },
    {
      stopName: 'Larnoo Drive/Reynolds Road',
      stopNumber: null,
      suburb: 'Doncaster East',
      stopGTFSID: '4105',
      arrivalTime: '12:48',
      arrivalTimeMinutes: 768,
      departureTime: '12:48',
      departureTimeMinutes: 768,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 1289.1
    },
    {
      stopName: 'Reynolds Road/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4106',
      arrivalTime: '12:49',
      arrivalTimeMinutes: 769,
      departureTime: '12:49',
      departureTimeMinutes: 769,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 1736.5
    },
    {
      stopName: 'Parklands Close/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4103',
      arrivalTime: '12:50',
      arrivalTimeMinutes: 770,
      departureTime: '12:50',
      departureTimeMinutes: 770,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 2102.81
    },
    {
      stopName: 'Era Court/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4107',
      arrivalTime: '12:50',
      arrivalTimeMinutes: 770,
      departureTime: '12:50',
      departureTimeMinutes: 770,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 2453.19
    },
    {
      stopName: 'Serpells Terrace/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4108',
      arrivalTime: '12:51',
      arrivalTimeMinutes: 771,
      departureTime: '12:51',
      departureTimeMinutes: 771,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 2859.72
    },
    {
      stopName: 'Donvale Retirement Village/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4109',
      arrivalTime: '12:52',
      arrivalTimeMinutes: 772,
      departureTime: '12:52',
      departureTimeMinutes: 772,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 3232.46
    },
    {
      stopName: 'Leslie Street/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4110',
      arrivalTime: '12:52',
      arrivalTimeMinutes: 772,
      departureTime: '12:52',
      departureTimeMinutes: 772,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 3456.94
    },
    {
      stopName: 'Old Warrandyte Road/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4111',
      arrivalTime: '12:53',
      arrivalTimeMinutes: 773,
      departureTime: '12:53',
      departureTimeMinutes: 773,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 3827.38
    },
    {
      stopName: 'Catjump Road/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4112',
      arrivalTime: '12:53',
      arrivalTimeMinutes: 773,
      departureTime: '12:53',
      departureTimeMinutes: 773,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 4098.02
    },
    {
      stopName: 'Charlwood Court/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4113',
      arrivalTime: '12:54',
      arrivalTimeMinutes: 774,
      departureTime: '12:54',
      departureTimeMinutes: 774,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 4395.05
    },
    {
      stopName: 'Donvale Aged Care/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4114',
      arrivalTime: '12:54',
      arrivalTimeMinutes: 774,
      departureTime: '12:54',
      departureTimeMinutes: 774,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 4650.73
    },
    {
      stopName: 'Pinetree Retirement Village/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4115',
      arrivalTime: '12:55',
      arrivalTimeMinutes: 775,
      departureTime: '12:55',
      departureTimeMinutes: 775,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 5024.36
    },
    {
      stopName: 'Solson Place/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4116',
      arrivalTime: '12:56',
      arrivalTimeMinutes: 776,
      departureTime: '12:56',
      departureTimeMinutes: 776,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 5429.39
    },
    {
      stopName: 'Heatherwood School/Springvale Road',
      stopNumber: null,
      suburb: 'Donvale',
      stopGTFSID: '4117',
      arrivalTime: '12:56',
      arrivalTimeMinutes: 776,
      departureTime: '12:56',
      departureTimeMinutes: 776,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 5636.31
    },
    {
      stopName: 'Ashwood Drive/Springvale Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '4118',
      arrivalTime: '12:57',
      arrivalTimeMinutes: 777,
      departureTime: '12:57',
      departureTimeMinutes: 777,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 6181.66
    },
    {
      stopName: 'Olwen Street/Springvale Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '4119',
      arrivalTime: '12:57',
      arrivalTimeMinutes: 777,
      departureTime: '12:57',
      departureTimeMinutes: 777,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 6383.6
    },
    {
      stopName: 'Tasman Avenue/Junction Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '1388',
      arrivalTime: '12:58',
      arrivalTimeMinutes: 778,
      departureTime: '12:58',
      departureTimeMinutes: 778,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 6925.41
    },
    {
      stopName: 'Lynette Street/Junction Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '1389',
      arrivalTime: '12:59',
      arrivalTimeMinutes: 779,
      departureTime: '12:59',
      departureTimeMinutes: 779,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 7251.78
    },
    {
      stopName: 'Barnsley Street/Junction Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '1390',
      arrivalTime: '13:00',
      arrivalTimeMinutes: 780,
      departureTime: '13:00',
      departureTimeMinutes: 780,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 7528.07
    },
    {
      stopName: 'Junction Road/Marchiori Road',
      stopNumber: null,
      suburb: 'Blackburn North',
      stopGTFSID: '2845',
      arrivalTime: '13:00',
      arrivalTimeMinutes: 780,
      departureTime: '13:00',
      departureTimeMinutes: 780,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 7887.11
    },
    {
      stopName: 'Glen Street/Marchiori Road',
      stopNumber: null,
      suburb: 'Blackburn North',
      stopGTFSID: '2849',
      arrivalTime: '13:01',
      arrivalTimeMinutes: 781,
      departureTime: '13:01',
      departureTimeMinutes: 781,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 8144.08
    },
    {
      stopName: 'Gunyah Road/Springfield Road',
      stopNumber: null,
      suburb: 'Blackburn North',
      stopGTFSID: '2905',
      arrivalTime: '13:01',
      arrivalTimeMinutes: 781,
      departureTime: '13:01',
      departureTimeMinutes: 781,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 8461.06
    },
    {
      stopName: 'Almer Avenue/Springfield Road',
      stopNumber: null,
      suburb: 'Blackburn North',
      stopGTFSID: '2937',
      arrivalTime: '13:02',
      arrivalTimeMinutes: 782,
      departureTime: '13:02',
      departureTimeMinutes: 782,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 8675.05
    },
    {
      stopName: 'Mardion Drive/Springfield Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '3032',
      arrivalTime: '13:02',
      arrivalTimeMinutes: 782,
      departureTime: '13:02',
      departureTimeMinutes: 782,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 8928.49
    },
    {
      stopName: 'Newman Road/Springfield Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '3078',
      arrivalTime: '13:03',
      arrivalTimeMinutes: 783,
      departureTime: '13:03',
      departureTimeMinutes: 783,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 9247.59
    },
    {
      stopName: 'Springvale Road/Springfield Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '3160',
      arrivalTime: '13:03',
      arrivalTimeMinutes: 783,
      departureTime: '13:03',
      departureTimeMinutes: 783,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 9393.88
    },
    {
      stopName: 'Springfield Road/Springvale Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '4120',
      arrivalTime: '13:04',
      arrivalTimeMinutes: 784,
      departureTime: '13:04',
      departureTimeMinutes: 784,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 9642.9
    },
    {
      stopName: 'Tunstall Avenue/Springvale Road',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '4121',
      arrivalTime: '13:05',
      arrivalTimeMinutes: 785,
      departureTime: '13:05',
      departureTimeMinutes: 785,
      stopConditions: { pickup: 0, dropoff: 0 },
      stopDistance: 9841.63
    },
    {
      stopName: 'Nunawading Railway Station/Station Street',
      stopNumber: null,
      suburb: 'Nunawading',
      stopGTFSID: '46543',
      arrivalTime: '13:07',
      arrivalTimeMinutes: 787,
      departureTime: '13:07',
      departureTimeMinutes: 787,
      stopConditions: { pickup: 1, dropoff: 0 },
      stopDistance: 10441.44
    }
  ],
  origin: 'The Pines Shopping Centre/Reynolds Road',
  departureTime: '12:45',
  destination: 'Nunawading Railway Station/Station Street',
  destinationArrivalTime: '13:07'
}